**This code is to use shape descriptors for classification using multi-layer perceptrons (MLPs):**

In [1]:
# Hyperparameters
MODEL = "padc_ann_with_dim_reduction"
DEVICE_ID = 1
SEED = 42
BATCH_SIZE = 512
EPOCHS = 100
LR = 1e-3
WEIGHT_DECAY = 1e-5
DROPOUT = 0.3
OPTIMIZER = "AdamW"
EXPLAINED_VARIANCE_THRESHOLD = 0.99

# Paths
LOG_DIR = f"./{MODEL}_logs/"
train_path = r"/home/c/choton/beemachine/codes/AG_vision_2026/4_shape_feature_analysis/Beemachine/bee_gt_shape_features_concise/bee_gt_features_train.csv"
val_path = r"/home/c/choton/beemachine/codes/AG_vision_2026/4_shape_feature_analysis/Beemachine/bee_gt_shape_features_concise/bee_gt_features_val.csv"
test_path = r"/home/c/choton/beemachine/codes/AG_vision_2026/4_shape_feature_analysis/Beemachine/bee_gt_shape_features_concise/bee_gt_features_test.csv"

In [9]:
import os
import json
import numpy as np
import pandas as pd
import random
from tqdm import tqdm
from sklearn.preprocessing import StandardScaler

import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader
from torch.optim.lr_scheduler import ReduceLROnPlateau

# ----------------- Dimensionality Reduction -----------------
from sklearn.decomposition import PCA, FastICA, NMF, TruncatedSVD
from sklearn.random_projection import GaussianRandomProjection, SparseRandomProjection

# Reproducibility
torch.manual_seed(SEED)
np.random.seed(SEED)
random.seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

In [3]:
# --- Replace NaNs within each species group ---
def fill_by_class_mean(df, class_col="species"):
    df = df.replace(0, np.nan)
    df = df.dropna(axis=1, how='all')
    df_numeric = df.select_dtypes(include=[np.number])
    # Fill NaNs in numeric columns using the class-wise mean
    df[df_numeric.columns] = df.groupby(class_col)[df_numeric.columns].transform(
        lambda x: x.fillna(x.mean())
    )
    # Step 2: fill any remaining NaNs globally (for columns that were all NaN in a class)
    df[df_numeric.columns] = df[df_numeric.columns].fillna(df[df_numeric.columns].mean())
    return df

def reduce_dimensions(X_train, X_val, X_test, method="PCA", n_components=100, random_state=SEED):
    """
    Apply dimensionality reduction on the dataset.
    Supported methods: "PCA", "ICA", "NMF", "TruncatedSVD", "GRP", "SRP"
    """
    if method == "PCA":
        reducer = PCA(n_components=n_components, random_state=random_state)
    elif method == "ICA":
        reducer = FastICA(n_components=n_components, random_state=random_state, max_iter=1000)
    elif method == "NMF":
        # NMF requires non-negative input
        X_train_nonneg = np.clip(X_train, 0, None)
        X_val_nonneg = np.clip(X_val, 0, None)
        X_test_nonneg = np.clip(X_test, 0, None)
        reducer = NMF(n_components=n_components, init='nndsvda', random_state=random_state, max_iter=1000)
        X_train = reducer.fit_transform(X_train_nonneg)
        X_val = reducer.transform(X_val_nonneg)
        X_test = reducer.transform(X_test_nonneg)
        return X_train, X_val, X_test, reducer
    elif method == "TruncatedSVD":
        reducer = TruncatedSVD(n_components=n_components, random_state=random_state)
    elif method == "GRP":
        reducer = GaussianRandomProjection(n_components=n_components, random_state=random_state)
    elif method == "SRP":
        reducer = SparseRandomProjection(n_components=n_components, random_state=random_state)
    else:
        raise ValueError(f"Unknown dimensionality reduction method: {method}")
    
    X_train_reduced = reducer.fit_transform(X_train)
    X_val_reduced   = reducer.transform(X_val)
    X_test_reduced  = reducer.transform(X_test)
    
    return X_train_reduced, X_val_reduced, X_test_reduced, reducer

def select_n_components_via_pca(X_train, explained_var_threshold=0.95, random_state=SEED, plot=False):
    """Use PCA to select optimal n_components based on explained variance."""
    pca_full = PCA(n_components=X_train.shape[1], random_state=random_state)
    pca_full.fit(X_train)
    cumulative_variance = np.cumsum(pca_full.explained_variance_ratio_)
    n_components_opt = np.argmax(cumulative_variance >= explained_var_threshold) + 1
    print(f"Optimal n_components (PCA, {explained_var_threshold*100}% variance): {n_components_opt}")
    
    # Optional plot
    if plot:
        plt.figure(figsize=(8,5))
        plt.plot(cumulative_variance, marker='o')
        plt.axhline(y=explained_var_threshold, color='r', linestyle='--')
        plt.xlabel('Number of components')
        plt.ylabel('Cumulative explained variance')
        plt.title('PCA Explained Variance')
        plt.grid(True)
        plt.show()    
    return n_components_opt

# ----------------- PyTorch Dataset -----------------
class ShapeFeatureDataset(Dataset):
    def __init__(self, X_np, y_np):
        self.X = torch.tensor(X_np, dtype=torch.float32)
        self.y = torch.tensor(y_np, dtype=torch.long)
    def __len__(self): 
        return len(self.X)
    def __getitem__(self, idx): 
        return self.X[idx], self.y[idx]

# The MLP classifier Network
class MLPClassifier(nn.Module):
    def __init__(self, input_dim, num_classes, dropout=0.3):
        super().__init__()
        mid_dim = input_dim
        if (input_dim // 2) > num_classes:
            mid_dim = input_dim // 2
        self.net = nn.Sequential(
            nn.Linear(input_dim, mid_dim),
            nn.LayerNorm(mid_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(mid_dim, num_classes)
        )
        # simple init
        for m in self.net:
            if isinstance(m, nn.Linear):
                nn.init.kaiming_normal_(m.weight)
                if m.bias is not None:
                    nn.init.zeros_(m.bias)

    def forward(self, x):
        return self.net(x)

# Training functions
def train_one_epoch(model, loader, criterion, optimizer, device):
    model.train()
    total_loss = 0
    correct = 0
    total = 0

    for X, y in loader:
        X, y = X.to(device), y.to(device)

        optimizer.zero_grad()
        outputs = model(X)
        loss = criterion(outputs, y)
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * X.size(0)

        preds = outputs.argmax(dim=1)
        correct += (preds == y).sum().item()
        total += y.size(0)

    return total_loss / total, correct / total


def validate_one_epoch(model, loader, criterion, device):
    model.eval()
    total_loss = 0
    correct = 0
    total = 0

    with torch.no_grad():
        for X, y in loader:
            X, y = X.to(device), y.to(device)
            outputs = model(X)
            loss = criterion(outputs, y)

            total_loss += loss.item() * X.size(0)

            preds = outputs.argmax(dim=1)
            correct += (preds == y).sum().item()
            total += y.size(0)

    return total_loss / total, correct / total

def train_model(model, train_loader, val_loader, criterion, optimizer, scheduler,
                device, epochs, log_dir):
    # Full training loop with logging and checkpointing 
    history = {"epoch": [], "train_loss": [], "val_loss": [], "train_acc": [], "val_acc": []}
    checkpoints_dir = os.path.join(log_dir, "checkpoints")
    os.makedirs(checkpoints_dir, exist_ok=True)

    # Initialize validation loss and start training
    best_val_loss = float("inf")
    print("Starting the first epoch...")

    for epoch in range(epochs):
        # ---- Training ----
        train_loss, train_acc = train_one_epoch(model, train_loader, criterion, optimizer, device)

        # ---- Validation ----
        val_loss, val_acc = validate_one_epoch(model, val_loader, criterion, device)

        # ---- Scheduler ----
        scheduler.step(val_loss)

        # ---- Logging ----
        history["epoch"].append(epoch + 1)
        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["train_acc"].append(train_acc)
        history["val_acc"].append(val_acc)

        # ---- Checkpoint ----
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_path = os.path.join(checkpoints_dir, "best_model.pth")
            torch.save(model.state_dict(), best_path)

            checkpoint_path = os.path.join(checkpoints_dir, f"checkpoint_epoch{epoch+1}.pth")
            torch.save({
                "epoch": epoch + 1,
                "model_state_dict": model.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "val_loss": val_loss
            }, checkpoint_path)
        
        print(f"\r Epoch {epoch+1}/{EPOCHS} | Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f} | Val Loss: {val_loss:.4f} | Val Acc: {val_acc:.4f}")    
    print("Training complete!")

    # ---- Save logs ----
    df = pd.DataFrame(history)
    csv_logfile = os.path.join(log_dir, "training_log.csv")
    json_logfile = os.path.join(log_dir, "training_log.json")

    df.to_csv(csv_logfile, index=False)
    with open(json_logfile, "w") as f:
        json.dump(history, f, indent=4)

    return history

In [5]:
train_df = pd.read_csv(train_path) 
val_df = pd.read_csv(val_path) 
test_df = pd.read_csv(test_path)

In [6]:
# Class names of every image
fulldata_path = r"/home/c/choton/beemachine/datasets/Bee_Full_Body_Segments/Images"
DATA_DIR = r"/home/c/choton/beemachine/datasets/Beemachine_Partwhole_v1/"

# Get list of classes
classes = os.listdir(fulldata_path)
species_dict = {}

for c in classes:
    images_path = os.path.join(fulldata_path, c)
    images = os.listdir(images_path)
    for image in images:
        image_name = image[:-4]
        species_dict[image_name] = c
image_names = list(species_dict.keys())
len(image_names)

8029

In [8]:
print(f"Shape of dataset, train: {train_df.shape}, val: {val_df.shape}, test: {test_df.shape}")

Shape of dataset, train: (34722, 938), val: (1158, 938), test: (771, 938)

In [11]:
count = 0
species_y = {}
for image_n in tqdm(image_names):
    for image_y in train_df['image']:
        # print(image_n)
        # print(image_y)
        # input()
        image_nx = image_n.replace("._", "-_")
        image_nx = image_nx.replace(".jpg", "")
        if image_nx in image_y:
            count += 1
            species_y[image_y] = species_dict[image_n]
print(count)
train_df['species'] = train_df['image'].map(species_y)
train_df

  0%|          | 0/8029 [00:00<?, ?it/s]

100%|██████████| 8029/8029 [01:50<00:00, 72.61it/s]

34866

,image,head_area,head_perimeter,head_aspect_ratio,head_extent,head_solidity,head_eccentricity,head_orientation,head_circularity,head_elongation,...,full_entropy,full_brisque,full_niqe,full_piqe,head_to_thorax_area,thorax_to_abdomen_area,head_to_total_area,thorax_to_total_area,abdomen_to_total_area,species
0,0090L0W0TQIQUR0Q3RIQCRIQTRQQS00QL0P0OQLQJRSQ9R...,4330.0,608.61730,3.586139,0.248822,0.568018,0.960334,1.295621,0.146896,0.721149,...,6.401090,60.094750,27.640350,41.000250,0.143003,23.202300,0.120566,0.843097,0.036337,Bombus_impatiens
1,0090L0W0TQIQUR0Q3RIQCRIQTRQQS00QL0P0OQLQJRSQ9R...,4325.0,606.82440,3.585948,0.248535,0.568854,0.960330,1.296722,0.147594,0.721134,...,6.392323,60.289352,24.562760,43.832634,0.142942,14.504794,0.117950,0.825161,0.056889,Bombus_impatiens
2,0090L0W0TQIQUR0Q3RIQCRIQTRQQS00QL0P0OQLQJRSQ9R...,4327.0,606.82440,3.584670,0.248650,0.569117,0.960301,-1.296543,0.147663,0.721034,...,6.391944,47.546585,27.722122,44.148280,0.143041,23.056402,0.120566,0.842877,0.036557,Bombus_impatiens
3,0090L0W0TQIQUR0Q3RIQCRIQTRQQS00QL0P0OQLQJRSQ9R...,4328.0,608.61730,3.587408,0.248707,0.567755,0.960363,-1.295801,0.146828,0.721247,...,6.400627,47.292450,24.678831,41.000793,0.142928,14.551177,0.117961,0.825320,0.056718,Bombus_impatiens
4,0090L0W0TQIQUR0Q3RIQCRIQTRQQS00QL0P0OQLQJRSQ9R...,4332.0,608.61730,3.587018,0.248937,0.568206,0.960354,0.274950,0.146964,0.721217,...,6.398315,56.920498,27.667301,43.878483,0.143164,23.063263,0.120658,0.842799,0.036543,Bombus_impatiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34717,Bombus_zonatus_GBIF_iNat_3058832608_2-jpg_jpg....,4248.0,488.43964,1.840455,0.564819,0.622965,0.839510,1.436783,0.223755,0.456656,...,9.348055,35.663630,25.897465,37.843678,0.106854,3.173799,0.075147,0.703267,0.221585,Bombus_zonatus
34718,Bombus_zonatus_GBIF_iNat_3058832608_2-jpg_jpg....,4248.0,488.43964,1.840455,0.564819,0.622965,0.839510,-1.436783,0.223755,0.456656,...,9.316640,53.308210,26.743814,37.511600,0.106854,3.173799,0.075147,0.703267,0.221585,Bombus_zonatus
34719,Bombus_zonatus_GBIF_iNat_3058832608_2-jpg_jpg....,4242.0,489.02542,1.842837,0.564021,0.622268,0.839964,-1.435658,0.222904,0.457359,...,9.353924,52.911057,25.226418,37.833157,0.106682,3.176212,0.075048,0.703471,0.221481,Bombus_zonatus
34720,Bombus_zonatus_GBIF_iNat_3058832608_2-jpg_jpg....,4245.0,488.43964,1.842244,0.564420,0.622708,0.839851,0.134523,0.223597,0.457184,...,9.333622,37.994225,25.915386,35.862720,0.106760,3.175371,0.075094,0.703391,0.221515,Bombus_zonatus
34721,Bombus_zonatus_GBIF_iNat_3058832608_2-jpg_jpg....,4245.0,489.02542,1.841044,0.564420,0.622525,0.839623,0.134629,0.223062,0.456830,...,9.347818,38.489445,25.613686,35.406563,0.106782,3.174479,0.075104,0.703337,0.221560,Bombus_zonatus

In [12]:
count = 0
species_y = {}
for image_n in tqdm(image_names):
    for image_y in val_df['image']:
        # print(image_n)
        # print(image_y)
        # input()
        image_nx = image_n.replace("._", "-_")
        image_nx = image_nx.replace(".jpg", "")
        if image_nx in image_y:
            count += 1
            species_y[image_y] = species_dict[image_n]
print(count)
val_df['species'] = val_df['image'].map(species_y)
val_df

100%|██████████| 8029/8029 [00:03<00:00, 2209.60it/s]

1161

,image,head_area,head_perimeter,head_aspect_ratio,head_extent,head_solidity,head_eccentricity,head_orientation,head_circularity,head_elongation,...,full_entropy,full_brisque,full_niqe,full_piqe,head_to_thorax_area,thorax_to_abdomen_area,head_to_total_area,thorax_to_total_area,abdomen_to_total_area,species
0,00903Q80CQ70TQX0AR403QU0Q050BRZQTQJKWR70JQN0YQ...,5410.0,434.57568,1.484547,0.497243,0.739172,0.739091,-1.247538,0.359978,0.326394,...,6.574201,69.938730,28.917168,43.730812,0.180586,16.606430,0.145540,0.805929,0.048531,Bombus_flavifrons
1,0090L09000N0Q0SQQ080FQFKCQHQ1R3K1RIQH0N0L0SQOR...,2058.0,449.34525,1.546949,0.172564,0.321864,0.762970,0.208325,0.128084,0.353566,...,4.861553,66.378494,25.980085,47.686066,0.129605,1.430412,0.070873,0.546835,0.382292,Bombus_terricola
2,0H6RLHERTZIZ2LRZWLZZ6LYLELYL2LHZFZ0R2L0RRHSRRH...,3315.0,355.98990,1.162912,0.458697,0.689333,0.510445,-1.497345,0.328714,0.140089,...,7.166333,40.585583,25.544678,38.450874,0.109363,3.333187,0.077596,0.709534,0.212870,Bombus_griseocollis
3,0HGRDZIROZ7RFZXRULHZ9L0R3ZYLNLKROZRZ9LYLNLZZTZ...,608.0,173.63351,8.116632,0.405063,0.683914,0.992381,1.451794,0.253423,0.876796,...,6.655105,32.683594,25.874298,41.878220,0.018505,72.210990,0.017925,0.968661,0.013414,Bombus_vosnesenskii
4,0K9KLKWKIKT0UQLSPQA0UQB0GQB04Q6K2Q2K6QUKPQC0KK...,8.0,8.00000,2.236068,1.000000,1.000000,0.894427,1.570796,1.570796,0.552786,...,5.211917,60.000885,23.613640,57.017180,0.000322,10.280810,0.000293,0.911087,0.088620,Bombus_melanopygus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1153,Bombus_sylvestris_iNat_21848423_1-jpg_jpg.rf.0...,3480.0,467.93713,1.185989,0.272492,0.429100,0.537634,-0.206154,0.199717,0.156822,...,7.189582,62.782967,24.507560,58.299995,0.142676,1.522059,0.079278,0.555654,0.365067,Bombus_sylvestris
1154,Bombus_sylvestris_iNat_27771888_01-jpg_jpg.rf....,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,5.752216,89.865560,26.728430,69.970680,0.000000,0.890869,0.000000,0.471143,0.528857,Bombus_sylvestris
1155,Bombus_sylvestris_iNat_36837121_01-jpg_jpg.rf....,4070.0,504.61120,1.798342,0.339167,0.596337,0.831137,0.148295,0.200859,0.443932,...,7.327914,60.891003,27.185130,51.417065,2.110996,0.075445,0.128989,0.061104,0.809907,Bombus_sylvestris
1156,Bombus_sylvestris_iNat_47607375_1-jpg_jpg.rf.3...,5225.0,453.34525,1.978194,0.424797,0.698810,0.862820,-1.515664,0.319476,0.494488,...,7.893108,30.526089,28.071922,33.448742,1.948173,0.108028,0.159620,0.081933,0.758447,Bombus_sylvestris
1157,Bombus_sylvestris_iNat_65486101_01-jpg_jpg.rf....,7179.0,796.54120,1.525048,0.370013,0.588974,0.755007,-1.279956,0.142186,0.344283,...,8.663421,52.528040,27.387337,46.852890,1.401601,0.242198,0.214625,0.153129,0.632246,Bombus_sylvestris

In [13]:
count = 0
species_y = {}
for image_n in tqdm(image_names):
    for image_y in test_df['image']:
        # print(image_n)
        # print(image_y)
        # input()
        image_nx = image_n.replace("._", "-_")
        image_nx = image_nx.replace(".jpg", "")
        if image_nx in image_y:
            count += 1
            species_y[image_y] = species_dict[image_n]
print(count)
test_df['species'] = test_df['image'].map(species_y)
test_df

100%|██████████| 8029/8029 [00:02<00:00, 3036.17it/s]

774

,image,head_area,head_perimeter,head_aspect_ratio,head_extent,head_solidity,head_eccentricity,head_orientation,head_circularity,head_elongation,...,full_entropy,full_brisque,full_niqe,full_piqe,head_to_thorax_area,thorax_to_abdomen_area,head_to_total_area,thorax_to_total_area,abdomen_to_total_area,species
0,0090L0W0TQIQURLQ9RSQ3RKQTRQQOR7Q3R60CQG0OQ80FQ...,4279.0,506.32693,1.777138,0.443144,0.666926,0.826659,-1.310267,0.209744,0.437298,...,6.121056,63.953552,29.595713,47.932377,0.198838,1.826825e+00,0.113867,0.572660,0.313473,Bombus_crotchii
1,0090Q0W0H0X0YQYKWR40S0SQURI0JQ70ARZQAR70CQHQUR...,2892.0,221.48022,1.697738,0.708824,0.953511,0.808119,-0.267619,0.740864,0.410981,...,7.187157,72.190110,29.266737,54.327305,0.088424,8.546120e+00,0.073354,0.829575,0.097070,Bombus_vagans
2,0K6KRKPKIKOK4KVKVQO08QPKKKD05QD0EQ9KSKA04QC04Q...,9156.0,400.45080,1.215336,0.726667,0.960151,0.568306,0.103841,0.717492,0.177182,...,5.984114,69.195910,26.606197,63.917778,0.377038,2.611183e+02,0.273044,0.724182,0.002773,Bombus_flavidus
3,0K9KLKWKIKT0UQB0PQLSWQF0NQY05KAKVQY05QC05Q6KQK...,2169.0,453.03763,1.134231,0.156178,0.303145,0.471896,1.255855,0.132801,0.118346,...,5.446256,79.839950,25.544370,59.388435,0.096606,1.111485e+01,0.081416,0.842761,0.075823,Bombus_perplexus
4,0L6ZLLEZILTH2HAHIHDHUHYHNHZREHJH7LNZMLFHWHVZQL...,7078.0,669.78890,1.372911,0.538006,0.701695,0.685174,-0.135562,0.198264,0.271621,...,6.088460,67.306000,27.478662,61.603825,0.247439,2.860500e+10,0.198358,0.801642,0.000000,Bombus_flavidus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
766,Bombus_trifasciatus_iNat_95727364_01-jpg_jpg.r...,7539.0,592.03760,2.363889,0.505159,0.795589,0.906115,-1.441886,0.270287,0.576968,...,7.466583,53.445713,25.307562,48.816837,20.542234,1.919255e-02,0.278933,0.013579,0.707489,Bombus_trifasciatus
767,Bombus_zonatus_GBIF_iNat_2236827425_2-jpg_jpg....,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,NaN,27.075386,100.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,Bombus_zonatus
768,Bombus_zonatus_GBIF_iNat_2236827425_3-jpg_jpg....,4149.0,622.22240,1.287401,0.235124,0.330361,0.629799,1.463304,0.134667,0.223242,...,4.817892,63.231586,26.097486,42.069763,0.334867,1.071614e+00,0.147646,0.440910,0.411444,Bombus_zonatus
769,Bombus_zonatus_GBIF_iNat_3058832608_1-jpg_jpg....,4461.0,550.49960,1.795978,0.319579,0.517457,0.830647,0.541462,0.184981,0.443200,...,7.733049,58.705130,27.434587,42.797490,1.946335,1.165463e-01,0.168856,0.086756,0.744389,Bombus_zonatus
770,YKBRFKBR3K1RFK1R50CQLQTQFKVRX0VR40TQI0Z060FRW0...,13872.0,747.29350,1.493415,0.535681,0.829814,0.742716,-0.687963,0.312152,0.330394,...,8.632905,54.519386,27.770890,43.666176,0.430073,5.305098e+00,0.265711,0.617829,0.116459,Bombus_kirbiellus

In [14]:
train_df = fill_by_class_mean(train_df, class_col="species")
val_df   = fill_by_class_mean(val_df, class_col="species")
test_df = fill_by_class_mean(test_df, class_col="species")

X_train = train_df.drop(columns=["image", "species"])
X_val = val_df.drop(columns=["image", "species"])
X_test = test_df.drop(columns=["image", "species"])
y_train = train_df["species"]
y_val = val_df["species"]
y_test = test_df["species"]

# --- Sanity check ---
assert not X_train.isna().any().any(), "NaNs remain in X_train!"
assert not X_val.isna().any().any(), "NaNs remain in X_val!"
assert not X_test.isna().any().any(), "NaNs remain in X_val!"
print("✅ Class-wise NaN imputation complete — no missing values remain.")

# ----------------- Standardize (important!) -----------------
scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train.values)
X_val_std  = scaler.transform(X_val.values)
X_test_std = scaler.transform(X_test.values)

# ----------------- Class mapping (use same mapping for train & val) -----------------
classes = sorted(y_train.unique())
class_to_idx = {c: i for i, c in enumerate(classes)}
num_classes = len(classes)

y_train_idx = y_train.map(class_to_idx).values
y_val_idx   = y_val.map(class_to_idx).values
y_test_idx = y_test.map(class_to_idx).values

✅ Class-wise NaN imputation complete — no missing values remain.

In [15]:
# Fit PCA with all components
pca_full = PCA(n_components=X_train_std.shape[1], random_state=SEED)
pca_full.fit(X_train_std)

# Cumulative explained variance
cumulative_variance = np.cumsum(pca_full.explained_variance_ratio_)

# Find number of components to explain desired variance (e.g., 95%)
explained_threshold = EXPLAINED_VARIANCE_THRESHOLD
n_components_opt = np.argmax(cumulative_variance >= explained_threshold) + 1

print(f"Optimal n_components for {explained_threshold*100}% variance: {n_components_opt}")

Optimal n_components for 99.0% variance: 637

In [16]:
n_components_opt = select_n_components_via_pca(X_train=X_train_std, explained_var_threshold=EXPLAINED_VARIANCE_THRESHOLD)

Optimal n_components (PCA, 99.0% variance): 637

In [17]:
%%time

# ----------------- Apply dimensionality reduction -----------------
DIM_REDUCTION_METHOD = "PCA"  # options: "PCA", "ICA", "NMF", "TruncatedSVD", "GRP", "SRP"
N_COMPONENTS = n_components_opt  # adjust as needed

X_train_np, X_val_np, X_test_np, reducer = reduce_dimensions(
    X_train_std, X_val_std, X_test_std,
    method=DIM_REDUCTION_METHOD,
    n_components=N_COMPONENTS
)

print(f"✅ Dimensionality reduction using {DIM_REDUCTION_METHOD} complete. New feature dim: {X_train_np.shape[1]}")

# ------------------ LOAD Datasets ------------------------
train_dataset = ShapeFeatureDataset(X_train_np, y_train_idx)
val_dataset   = ShapeFeatureDataset(X_val_np,   y_val_idx)
test_dataset  = ShapeFeatureDataset(X_test_np,   y_test_idx)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0, pin_memory=False)
val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE, shuffle=False, num_workers=0, pin_memory=False)
test_loader  = DataLoader(test_dataset,   batch_size=BATCH_SIZE, shuffle=False, num_workers=0, pin_memory=False)

# Load model and optimizers
input_dim = X_train_np.shape[1]
num_classes = len(classes)
device = torch.device(f"cuda:{DEVICE_ID}")
model = MLPClassifier(input_dim, num_classes).to(device)
criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
optimizer = torch.optim.Adam(model.parameters(), lr=LR)
scheduler = ReduceLROnPlateau(optimizer, mode="min", factor=0.5, patience=2)

history = train_model(
    model=model,
    train_loader=train_loader,
    val_loader=val_loader,
    criterion=criterion,
    optimizer=optimizer,
    scheduler=scheduler,
    device=device,
    epochs=EPOCHS,
    log_dir=LOG_DIR+f"_{DIM_REDUCTION_METHOD}"
)

# ----------------- Load best model -----------------
# best_model_path = os.path.join(LOG_DIR, "checkpoints", "best_model.pth")
# model.load_state_dict(torch.load(best_model_path, map_location=device))
# model.to(device)
model.eval()

# ----------------- Evaluate on test set -----------------
def evaluate_test(model, loader, device):
    correct = 0
    total = 0
    with torch.no_grad():
        for X, y in loader:
            X, y = X.to(device), y.to(device)
            outputs = model(X)
            preds = outputs.argmax(dim=1)
            correct += (preds == y).sum().item()
            total += y.size(0)
    return correct / total

test_acc = evaluate_test(model, test_loader, device)
print("Test accuracy:", test_acc)

✅ Dimensionality reduction using PCA complete. New feature dim: 637
Starting the first epoch...
 Epoch 1/100 | Train Loss: 4.3610 | Train Acc: 0.1363 | Val Loss: 3.9429 | Val Acc: 0.1926
 Epoch 2/100 | Train Loss: 3.2457 | Train Acc: 0.3376 | Val Loss: 3.6657 | Val Acc: 0.2392
 Epoch 3/100 | Train Loss: 2.6004 | Train Acc: 0.5141 | Val Loss: 3.5524 | Val Acc: 0.2677
 Epoch 4/100 | Train Loss: 2.1286 | Train Acc: 0.6538 | Val Loss: 3.5283 | Val Acc: 0.2617
 Epoch 5/100 | Train Loss: 1.8080 | Train Acc: 0.7631 | Val Loss: 3.5630 | Val Acc: 0.2625
 Epoch 6/100 | Train Loss: 1.6015 | Train Acc: 0.8300 | Val Loss: 3.5986 | Val Acc: 0.2763
 Epoch 7/100 | Train Loss: 1.4645 | Train Acc: 0.8797 | Val Loss: 3.6499 | Val Acc: 0.2694
 Epoch 8/100 | Train Loss: 1.3686 | Train Acc: 0.9156 | Val Loss: 3.6698 | Val Acc: 0.2694
 Epoch 9/100 | Train Loss: 1.3370 | Train Acc: 0.9245 | Val Loss: 3.6811 | Val Acc: 0.2737
 Epoch 10/100 | Train Loss: 1.2994 | Train Acc: 0.9370 | Val Loss: 3.6969 | Val Acc: 0.2642
 Epoch 11/100 | Train Loss: 1.2719 | Train Acc: 0.9480 | Val Loss: 3.7053 | Val Acc: 0.2677
 Epoch 12/100 | Train Loss: 1.2596 | Train Acc: 0.9512 | Val Loss: 3.7158 | Val Acc: 0.2591
 Epoch 13/100 | Train Loss: 1.2490 | Train Acc: 0.9552 | Val Loss: 3.7217 | Val Acc: 0.2625
 Epoch 14/100 | Train Loss: 1.2385 | Train Acc: 0.9582 | Val Loss: 3.7283 | Val Acc: 0.2625
 Epoch 15/100 | Train Loss: 1.2321 | Train Acc: 0.9601 | Val Loss: 3.7317 | Val Acc: 0.2677
 Epoch 16/100 | Train Loss: 1.2278 | Train Acc: 0.9607 | Val Loss: 3.7347 | Val Acc: 0.2642
 Epoch 17/100 | Train Loss: 1.2187 | Train Acc: 0.9645 | Val Loss: 3.7367 | Val Acc: 0.2642
 Epoch 18/100 | Train Loss: 1.2197 | Train Acc: 0.9632 | Val Loss: 3.7398 | Val Acc: 0.2634
 Epoch 19/100 | Train Loss: 1.2173 | Train Acc: 0.9633 | Val Loss: 3.7412 | Val Acc: 0.2677
 Epoch 20/100 | Train Loss: 1.2135 | Train Acc: 0.9653 | Val Loss: 3.7420 | Val Acc: 0.2651
 Epoch 21/100 | Train Loss: 1.2123 | Train Acc: 0.9662 | Val Loss: 3.7433 | Val Acc: 0.2660
 Epoch 22/100 | Train Loss: 1.2104 | Train Acc: 0.9656 | Val Loss: 3.7446 | Val Acc: 0.2651
 Epoch 23/100 | Train Loss: 1.2097 | Train Acc: 0.9665 | Val Loss: 3.7453 | Val Acc: 0.2642
 Epoch 24/100 | Train Loss: 1.2084 | Train Acc: 0.9670 | Val Loss: 3.7458 | Val Acc: 0.2651
 Epoch 25/100 | Train Loss: 1.2077 | Train Acc: 0.9676 | Val Loss: 3.7468 | Val Acc: 0.2634
 Epoch 26/100 | Train Loss: 1.2090 | Train Acc: 0.9669 | Val Loss: 3.7469 | Val Acc: 0.2634
 Epoch 27/100 | Train Loss: 1.2074 | Train Acc: 0.9681 | Val Loss: 3.7473 | Val Acc: 0.2642
 Epoch 28/100 | Train Loss: 1.2083 | Train Acc: 0.9662 | Val Loss: 3.7474 | Val Acc: 0.2642
 Epoch 29/100 | Train Loss: 1.2089 | Train Acc: 0.9665 | Val Loss: 3.7476 | Val Acc: 0.2651
 Epoch 30/100 | Train Loss: 1.2076 | Train Acc: 0.9670 | Val Loss: 3.7478 | Val Acc: 0.2642
 Epoch 31/100 | Train Loss: 1.2072 | Train Acc: 0.9677 | Val Loss: 3.7479 | Val Acc: 0.2651
 Epoch 32/100 | Train Loss: 1.2079 | Train Acc: 0.9679 | Val Loss: 3.7480 | Val Acc: 0.2642
 Epoch 33/100 | Train Loss: 1.2053 | Train Acc: 0.9672 | Val Loss: 3.7481 | Val Acc: 0.2651
 Epoch 34/100 | Train Loss: 1.2045 | Train Acc: 0.9675 | Val Loss: 3.7482 | Val Acc: 0.2651
 Epoch 35/100 | Train Loss: 1.2067 | Train Acc: 0.9679 | Val Loss: 3.7482 | Val Acc: 0.2651
 Epoch 36/100 | Train Loss: 1.2058 | Train Acc: 0.9690 | Val Loss: 3.7483 | Val Acc: 0.2651
 Epoch 37/100 | Train Loss: 1.2045 | Train Acc: 0.9680 | Val Loss: 3.7483 | Val Acc: 0.2642
 Epoch 38/100 | Train Loss: 1.2069 | Train Acc: 0.9676 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 39/100 | Train Loss: 1.2051 | Train Acc: 0.9694 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 40/100 | Train Loss: 1.2053 | Train Acc: 0.9677 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 41/100 | Train Loss: 1.2058 | Train Acc: 0.9679 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 42/100 | Train Loss: 1.2078 | Train Acc: 0.9665 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 43/100 | Train Loss: 1.2041 | Train Acc: 0.9673 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 44/100 | Train Loss: 1.2081 | Train Acc: 0.9660 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 45/100 | Train Loss: 1.2044 | Train Acc: 0.9694 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 46/100 | Train Loss: 1.2066 | Train Acc: 0.9681 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 47/100 | Train Loss: 1.2031 | Train Acc: 0.9691 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 48/100 | Train Loss: 1.2077 | Train Acc: 0.9680 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 49/100 | Train Loss: 1.2060 | Train Acc: 0.9674 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 50/100 | Train Loss: 1.2045 | Train Acc: 0.9678 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 51/100 | Train Loss: 1.2057 | Train Acc: 0.9680 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 52/100 | Train Loss: 1.2037 | Train Acc: 0.9678 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 53/100 | Train Loss: 1.2061 | Train Acc: 0.9671 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 54/100 | Train Loss: 1.2028 | Train Acc: 0.9687 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 55/100 | Train Loss: 1.2056 | Train Acc: 0.9670 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 56/100 | Train Loss: 1.2061 | Train Acc: 0.9667 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 57/100 | Train Loss: 1.2065 | Train Acc: 0.9670 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 58/100 | Train Loss: 1.2104 | Train Acc: 0.9667 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 59/100 | Train Loss: 1.2070 | Train Acc: 0.9664 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 60/100 | Train Loss: 1.2056 | Train Acc: 0.9676 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 61/100 | Train Loss: 1.2039 | Train Acc: 0.9682 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 62/100 | Train Loss: 1.2086 | Train Acc: 0.9663 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 63/100 | Train Loss: 1.2064 | Train Acc: 0.9661 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 64/100 | Train Loss: 1.2058 | Train Acc: 0.9688 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 65/100 | Train Loss: 1.2059 | Train Acc: 0.9681 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 66/100 | Train Loss: 1.2055 | Train Acc: 0.9676 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 67/100 | Train Loss: 1.2034 | Train Acc: 0.9682 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 68/100 | Train Loss: 1.2051 | Train Acc: 0.9686 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 69/100 | Train Loss: 1.2055 | Train Acc: 0.9685 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 70/100 | Train Loss: 1.2059 | Train Acc: 0.9685 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 71/100 | Train Loss: 1.2054 | Train Acc: 0.9694 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 72/100 | Train Loss: 1.2071 | Train Acc: 0.9683 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 73/100 | Train Loss: 1.2075 | Train Acc: 0.9673 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 74/100 | Train Loss: 1.2031 | Train Acc: 0.9682 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 75/100 | Train Loss: 1.2076 | Train Acc: 0.9655 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 76/100 | Train Loss: 1.2080 | Train Acc: 0.9660 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 77/100 | Train Loss: 1.2073 | Train Acc: 0.9668 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 78/100 | Train Loss: 1.2049 | Train Acc: 0.9686 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 79/100 | Train Loss: 1.2061 | Train Acc: 0.9684 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 80/100 | Train Loss: 1.2048 | Train Acc: 0.9677 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 81/100 | Train Loss: 1.2063 | Train Acc: 0.9676 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 82/100 | Train Loss: 1.2074 | Train Acc: 0.9670 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 83/100 | Train Loss: 1.2059 | Train Acc: 0.9676 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 84/100 | Train Loss: 1.2054 | Train Acc: 0.9688 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 85/100 | Train Loss: 1.2055 | Train Acc: 0.9696 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 86/100 | Train Loss: 1.2066 | Train Acc: 0.9680 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 87/100 | Train Loss: 1.2066 | Train Acc: 0.9685 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 88/100 | Train Loss: 1.2060 | Train Acc: 0.9673 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 89/100 | Train Loss: 1.2039 | Train Acc: 0.9691 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 90/100 | Train Loss: 1.2036 | Train Acc: 0.9690 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 91/100 | Train Loss: 1.2048 | Train Acc: 0.9683 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 92/100 | Train Loss: 1.2062 | Train Acc: 0.9671 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 93/100 | Train Loss: 1.2042 | Train Acc: 0.9681 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 94/100 | Train Loss: 1.2058 | Train Acc: 0.9673 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 95/100 | Train Loss: 1.2029 | Train Acc: 0.9687 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 96/100 | Train Loss: 1.2015 | Train Acc: 0.9692 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 97/100 | Train Loss: 1.2062 | Train Acc: 0.9679 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 98/100 | Train Loss: 1.2081 | Train Acc: 0.9672 | Val Loss: 3.7484 | Val Acc: 0.2642
 Epoch 99/100 | Train Loss: 1.2042 | Train Acc: 0.9685 | Val Loss: 3.7485 | Val Acc: 0.2642
 Epoch 100/100 | Train Loss: 1.2044 | Train Acc: 0.9683 | Val Loss: 3.7485 | Val Acc: 0.2642
Training complete!
Test accuracy: 0.23476005188067445
CPU times: user 5min 25s, sys: 2.16 s, total: 5min 28s
Wall time: 1min 14s

In [18]:
%%time

# ----------------- Apply dimensionality reduction -----------------
DIM_REDUCTION_METHOD = "ICA"  # options: "PCA", "ICA", "NMF", "TruncatedSVD", "GRP", "SRP"

X_train_np, X_val_np, X_test_np, reducer = reduce_dimensions(
    X_train_std, X_val_std, X_test_std,
    method=DIM_REDUCTION_METHOD,
    n_components=n_components_opt
)

print(f"✅ Dimensionality reduction using {DIM_REDUCTION_METHOD} complete. New feature dim: {X_train_np.shape[1]}")

# ------------------ LOAD Datasets ------------------------
train_dataset = ShapeFeatureDataset(X_train_np, y_train_idx)
val_dataset   = ShapeFeatureDataset(X_val_np,   y_val_idx)
test_dataset  = ShapeFeatureDataset(X_test_np,   y_test_idx)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0, pin_memory=False)
val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE, shuffle=False, num_workers=0, pin_memory=False)
test_loader  = DataLoader(test_dataset,   batch_size=BATCH_SIZE, shuffle=False, num_workers=0, pin_memory=False)

# Load model and optimizers
input_dim = X_train_np.shape[1]
num_classes = len(classes)
device = torch.device(f"cuda:{DEVICE_ID}")
model = MLPClassifier(input_dim, num_classes).to(device)
criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
optimizer = torch.optim.Adam(model.parameters(), lr=LR)
scheduler = ReduceLROnPlateau(optimizer, mode="min", factor=0.5, patience=2)

history = train_model(
    model=model,
    train_loader=train_loader,
    val_loader=val_loader,
    criterion=criterion,
    optimizer=optimizer,
    scheduler=scheduler,
    device=device,
    epochs=EPOCHS,
    log_dir=LOG_DIR+f"_{DIM_REDUCTION_METHOD}"
)

# ----------------- Load best model -----------------
# best_model_path = os.path.join(LOG_DIR, "checkpoints", "best_model.pth")
# model.load_state_dict(torch.load(best_model_path, map_location=device))
# model.to(device)
model.eval()

# ----------------- Evaluate on test set -----------------
def evaluate_test(model, loader, device):
    correct = 0
    total = 0
    with torch.no_grad():
        for X, y in loader:
            X, y = X.to(device), y.to(device)
            outputs = model(X)
            preds = outputs.argmax(dim=1)
            correct += (preds == y).sum().item()
            total += y.size(0)
    return correct / total

test_acc = evaluate_test(model, test_loader, device)
print("Test accuracy:", test_acc)

CPU times: user 20h 17min 17s, sys: 35.2 s, total: 20h 17min 52s
Wall time: 1h 47min 25s

In [ ]:
%%time

# ----------------- Apply dimensionality reduction -----------------
DIM_REDUCTION_METHOD = "TruncatedSVD"  # options: "PCA", "ICA", "NMF", "TruncatedSVD", "GRP", "SRP"

X_train_np, X_val_np, X_test_np, reducer = reduce_dimensions(
    X_train_std, X_val_std, X_test_std,
    method=DIM_REDUCTION_METHOD,
    n_components=n_components_opt
)

print(f"✅ Dimensionality reduction using {DIM_REDUCTION_METHOD} complete. New feature dim: {X_train_np.shape[1]}")

# ------------------ LOAD Datasets ------------------------
train_dataset = ShapeFeatureDataset(X_train_np, y_train_idx)
val_dataset   = ShapeFeatureDataset(X_val_np,   y_val_idx)
test_dataset  = ShapeFeatureDataset(X_test_np,   y_test_idx)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0, pin_memory=False)
val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE, shuffle=False, num_workers=0, pin_memory=False)
test_loader  = DataLoader(test_dataset,   batch_size=BATCH_SIZE, shuffle=False, num_workers=0, pin_memory=False)

# Load model and optimizers
input_dim = X_train_np.shape[1]
num_classes = len(classes)
device = torch.device(f"cuda:{DEVICE_ID}")
model = MLPClassifier(input_dim, num_classes).to(device)
criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
optimizer = torch.optim.Adam(model.parameters(), lr=LR)
scheduler = ReduceLROnPlateau(optimizer, mode="min", factor=0.5, patience=2)

history = train_model(
    model=model,
    train_loader=train_loader,
    val_loader=val_loader,
    criterion=criterion,
    optimizer=optimizer,
    scheduler=scheduler,
    device=device,
    epochs=EPOCHS,
    log_dir=LOG_DIR+f"_{DIM_REDUCTION_METHOD}"
)

# ----------------- Load best model -----------------
# best_model_path = os.path.join(LOG_DIR, "checkpoints", "best_model.pth")
# model.load_state_dict(torch.load(best_model_path, map_location=device))
# model.to(device)
model.eval()

# ----------------- Evaluate on test set -----------------
def evaluate_test(model, loader, device):
    correct = 0
    total = 0
    with torch.no_grad():
        for X, y in loader:
            X, y = X.to(device), y.to(device)
            outputs = model(X)
            preds = outputs.argmax(dim=1)
            correct += (preds == y).sum().item()
            total += y.size(0)
    return correct / total

test_acc = evaluate_test(model, test_loader, device)
print("Test accuracy:", test_acc)

✅ Dimensionality reduction using TruncatedSVD complete. New feature dim: 634
Starting the first epoch...
 Epoch 1/100 | Train Loss: 3.6821 | Train Acc: 0.1906 | Val Loss: 2.9758 | Val Acc: 0.3385
 Epoch 2/100 | Train Loss: 2.7183 | Train Acc: 0.3941 | Val Loss: 2.4811 | Val Acc: 0.4648
 Epoch 3/100 | Train Loss: 2.2366 | Train Acc: 0.5401 | Val Loss: 2.1237 | Val Acc: 0.5839
 Epoch 4/100 | Train Loss: 1.8918 | Train Acc: 0.6581 | Val Loss: 1.8572 | Val Acc: 0.6771
 Epoch 5/100 | Train Loss: 1.6387 | Train Acc: 0.7523 | Val Loss: 1.6488 | Val Acc: 0.7504
 Epoch 6/100 | Train Loss: 1.4611 | Train Acc: 0.8197 | Val Loss: 1.4924 | Val Acc: 0.8183
 Epoch 7/100 | Train Loss: 1.3338 | Train Acc: 0.8687 | Val Loss: 1.3702 | Val Acc: 0.8595
 Epoch 8/100 | Train Loss: 1.2410 | Train Acc: 0.9039 | Val Loss: 1.2782 | Val Acc: 0.8944
 Epoch 9/100 | Train Loss: 1.1828 | Train Acc: 0.9258 | Val Loss: 1.2111 | Val Acc: 0.9164
 Epoch 10/100 | Train Loss: 1.1411 | Train Acc: 0.9417 | Val Loss: 1.1656 | Val Acc: 0.9289
 Epoch 11/100 | Train Loss: 1.1012 | Train Acc: 0.9564 | Val Loss: 1.1288 | Val Acc: 0.9385
 Epoch 12/100 | Train Loss: 1.0745 | Train Acc: 0.9653 | Val Loss: 1.0983 | Val Acc: 0.9470
 Epoch 13/100 | Train Loss: 1.0504 | Train Acc: 0.9735 | Val Loss: 1.0756 | Val Acc: 0.9534
 Epoch 14/100 | Train Loss: 1.0337 | Train Acc: 0.9772 | Val Loss: 1.0538 | Val Acc: 0.9605
 Epoch 15/100 | Train Loss: 1.0208 | Train Acc: 0.9802 | Val Loss: 1.0437 | Val Acc: 0.9612
 Epoch 16/100 | Train Loss: 1.0073 | Train Acc: 0.9851 | Val Loss: 1.0285 | Val Acc: 0.9655
 Epoch 17/100 | Train Loss: 0.9972 | Train Acc: 0.9853 | Val Loss: 1.0175 | Val Acc: 0.9662
 Epoch 18/100 | Train Loss: 0.9860 | Train Acc: 0.9885 | Val Loss: 1.0078 | Val Acc: 0.9708
 Epoch 19/100 | Train Loss: 0.9789 | Train Acc: 0.9896 | Val Loss: 0.9980 | Val Acc: 0.9701
 Epoch 20/100 | Train Loss: 0.9719 | Train Acc: 0.9910 | Val Loss: 0.9937 | Val Acc: 0.9723
 Epoch 21/100 | Train Loss: 0.9645 | Train Acc: 0.9918 | Val Loss: 0.9867 | Val Acc: 0.9723
 Epoch 22/100 | Train Loss: 0.9598 | Train Acc: 0.9923 | Val Loss: 0.9805 | Val Acc: 0.9733
 Epoch 23/100 | Train Loss: 0.9532 | Train Acc: 0.9923 | Val Loss: 0.9760 | Val Acc: 0.9748
 Epoch 24/100 | Train Loss: 0.9476 | Train Acc: 0.9949 | Val Loss: 0.9688 | Val Acc: 0.9758
 Epoch 25/100 | Train Loss: 0.9414 | Train Acc: 0.9947 | Val Loss: 0.9645 | Val Acc: 0.9762
 Epoch 26/100 | Train Loss: 0.9379 | Train Acc: 0.9954 | Val Loss: 0.9617 | Val Acc: 0.9740
 Epoch 27/100 | Train Loss: 0.9340 | Train Acc: 0.9962 | Val Loss: 0.9579 | Val Acc: 0.9765
 Epoch 28/100 | Train Loss: 0.9294 | Train Acc: 0.9964 | Val Loss: 0.9552 | Val Acc: 0.9776
 Epoch 29/100 | Train Loss: 0.9276 | Train Acc: 0.9970 | Val Loss: 0.9502 | Val Acc: 0.9790
 Epoch 30/100 | Train Loss: 0.9235 | Train Acc: 0.9966 | Val Loss: 0.9472 | Val Acc: 0.9787
 Epoch 31/100 | Train Loss: 0.9187 | Train Acc: 0.9974 | Val Loss: 0.9431 | Val Acc: 0.9783
 Epoch 32/100 | Train Loss: 0.9153 | Train Acc: 0.9980 | Val Loss: 0.9400 | Val Acc: 0.9801
 Epoch 33/100 | Train Loss: 0.9134 | Train Acc: 0.9977 | Val Loss: 0.9371 | Val Acc: 0.9787
 Epoch 34/100 | Train Loss: 0.9109 | Train Acc: 0.9976 | Val Loss: 0.9373 | Val Acc: 0.9787
 Epoch 35/100 | Train Loss: 0.9084 | Train Acc: 0.9981 | Val Loss: 0.9341 | Val Acc: 0.9794
 Epoch 36/100 | Train Loss: 0.9035 | Train Acc: 0.9980 | Val Loss: 0.9313 | Val Acc: 0.9804
 Epoch 37/100 | Train Loss: 0.9021 | Train Acc: 0.9983 | Val Loss: 0.9290 | Val Acc: 0.9804
 Epoch 38/100 | Train Loss: 0.9006 | Train Acc: 0.9982 | Val Loss: 0.9277 | Val Acc: 0.9797
 Epoch 39/100 | Train Loss: 0.8965 | Train Acc: 0.9990 | Val Loss: 0.9255 | Val Acc: 0.9819
 Epoch 40/100 | Train Loss: 0.8948 | Train Acc: 0.9987 | Val Loss: 0.9229 | Val Acc: 0.9829
 Epoch 41/100 | Train Loss: 0.8948 | Train Acc: 0.9990 | Val Loss: 0.9200 | Val Acc: 0.9840
 Epoch 42/100 | Train Loss: 0.8920 | Train Acc: 0.9990 | Val Loss: 0.9185 | Val Acc: 0.9836
 Epoch 43/100 | Train Loss: 0.8898 | Train Acc: 0.9990 | Val Loss: 0.9162 | Val Acc: 0.9829
 Epoch 44/100 | Train Loss: 0.8893 | Train Acc: 0.9987 | Val Loss: 0.9158 | Val Acc: 0.9844
 Epoch 45/100 | Train Loss: 0.8874 | Train Acc: 0.9992 | Val Loss: 0.9138 | Val Acc: 0.9858
 Epoch 46/100 | Train Loss: 0.8857 | Train Acc: 0.9991 | Val Loss: 0.9120 | Val Acc: 0.9847
 Epoch 47/100 | Train Loss: 0.8838 | Train Acc: 0.9987 | Val Loss: 0.9128 | Val Acc: 0.9844
 Epoch 48/100 | Train Loss: 0.8827 | Train Acc: 0.9992 | Val Loss: 0.9098 | Val Acc: 0.9840
 Epoch 49/100 | Train Loss: 0.8809 | Train Acc: 0.9993 | Val Loss: 0.9084 | Val Acc: 0.9833
 Epoch 50/100 | Train Loss: 0.8784 | Train Acc: 0.9996 | Val Loss: 0.9066 | Val Acc: 0.9847
 Epoch 51/100 | Train Loss: 0.8786 | Train Acc: 0.9997 | Val Loss: 0.9052 | Val Acc: 0.9840
 Epoch 52/100 | Train Loss: 0.8760 | Train Acc: 0.9992 | Val Loss: 0.9047 | Val Acc: 0.9858
 Epoch 53/100 | Train Loss: 0.8770 | Train Acc: 0.9993 | Val Loss: 0.9044 | Val Acc: 0.9858
 Epoch 54/100 | Train Loss: 0.8748 | Train Acc: 0.9995 | Val Loss: 0.9055 | Val Acc: 0.9851
 Epoch 55/100 | Train Loss: 0.8732 | Train Acc: 0.9995 | Val Loss: 0.9019 | Val Acc: 0.9847
 Epoch 56/100 | Train Loss: 0.8722 | Train Acc: 0.9997 | Val Loss: 0.9005 | Val Acc: 0.9854
 Epoch 57/100 | Train Loss: 0.8710 | Train Acc: 0.9999 | Val Loss: 0.8996 | Val Acc: 0.9858
 Epoch 58/100 | Train Loss: 0.8690 | Train Acc: 0.9997 | Val Loss: 0.8994 | Val Acc: 0.9868
 Epoch 59/100 | Train Loss: 0.8696 | Train Acc: 0.9994 | Val Loss: 0.8985 | Val Acc: 0.9865
 Epoch 60/100 | Train Loss: 0.8676 | Train Acc: 0.9996 | Val Loss: 0.8971 | Val Acc: 0.9854
 Epoch 61/100 | Train Loss: 0.8668 | Train Acc: 0.9998 | Val Loss: 0.8985 | Val Acc: 0.9847
 Epoch 62/100 | Train Loss: 0.8647 | Train Acc: 0.9997 | Val Loss: 0.8956 | Val Acc: 0.9861
 Epoch 63/100 | Train Loss: 0.8643 | Train Acc: 0.9996 | Val Loss: 0.8938 | Val Acc: 0.9858
 Epoch 64/100 | Train Loss: 0.8653 | Train Acc: 0.9997 | Val Loss: 0.8928 | Val Acc: 0.9876
 Epoch 65/100 | Train Loss: 0.8643 | Train Acc: 0.9993 | Val Loss: 0.8930 | Val Acc: 0.9868
 Epoch 66/100 | Train Loss: 0.8632 | Train Acc: 0.9998 | Val Loss: 0.8934 | Val Acc: 0.9868
 Epoch 67/100 | Train Loss: 0.8624 | Train Acc: 0.9997 | Val Loss: 0.8905 | Val Acc: 0.9854
 Epoch 68/100 | Train Loss: 0.8614 | Train Acc: 0.9998 | Val Loss: 0.8903 | Val Acc: 0.9865
 Epoch 69/100 | Train Loss: 0.8602 | Train Acc: 0.9996 | Val Loss: 0.8895 | Val Acc: 0.9847
 Epoch 70/100 | Train Loss: 0.8606 | Train Acc: 0.9995 | Val Loss: 0.8882 | Val Acc: 0.9851
 Epoch 71/100 | Train Loss: 0.8585 | Train Acc: 0.9996 | Val Loss: 0.8851 | Val Acc: 0.9868
 Epoch 72/100 | Train Loss: 0.8576 | Train Acc: 0.9997 | Val Loss: 0.8854 | Val Acc: 0.9872
 Epoch 73/100 | Train Loss: 0.8568 | Train Acc: 0.9996 | Val Loss: 0.8857 | Val Acc: 0.9872
 Epoch 74/100 | Train Loss: 0.8571 | Train Acc: 0.9996 | Val Loss: 0.8849 | Val Acc: 0.9851
 Epoch 75/100 | Train Loss: 0.8558 | Train Acc: 0.9998 | Val Loss: 0.8840 | Val Acc: 0.9876
 Epoch 76/100 | Train Loss: 0.8559 | Train Acc: 0.9998 | Val Loss: 0.8823 | Val Acc: 0.9876
 Epoch 77/100 | Train Loss: 0.8548 | Train Acc: 1.0000 | Val Loss: 0.8816 | Val Acc: 0.9883
 Epoch 78/100 | Train Loss: 0.8534 | Train Acc: 0.9997 | Val Loss: 0.8818 | Val Acc: 0.9876
 Epoch 79/100 | Train Loss: 0.8527 | Train Acc: 0.9998 | Val Loss: 0.8804 | Val Acc: 0.9883
 Epoch 80/100 | Train Loss: 0.8520 | Train Acc: 0.9999 | Val Loss: 0.8806 | Val Acc: 0.9876
 Epoch 81/100 | Train Loss: 0.8527 | Train Acc: 0.9998 | Val Loss: 0.8790 | Val Acc: 0.9872
 Epoch 82/100 | Train Loss: 0.8519 | Train Acc: 0.9998 | Val Loss: 0.8784 | Val Acc: 0.9886
 Epoch 83/100 | Train Loss: 0.8513 | Train Acc: 0.9999 | Val Loss: 0.8790 | Val Acc: 0.9886
 Epoch 84/100 | Train Loss: 0.8508 | Train Acc: 0.9997 | Val Loss: 0.8781 | Val Acc: 0.9904
 Epoch 85/100 | Train Loss: 0.8513 | Train Acc: 0.9999 | Val Loss: 0.8775 | Val Acc: 0.9883
 Epoch 86/100 | Train Loss: 0.8500 | Train Acc: 0.9996 | Val Loss: 0.8779 | Val Acc: 0.9890
 Epoch 87/100 | Train Loss: 0.8489 | Train Acc: 0.9997 | Val Loss: 0.8760 | Val Acc: 0.9897
 Epoch 88/100 | Train Loss: 0.8487 | Train Acc: 0.9999 | Val Loss: 0.8766 | Val Acc: 0.9872
 Epoch 89/100 | Train Loss: 0.8486 | Train Acc: 0.9998 | Val Loss: 0.8743 | Val Acc: 0.9879
 Epoch 90/100 | Train Loss: 0.8481 | Train Acc: 0.9999 | Val Loss: 0.8749 | Val Acc: 0.9883
 Epoch 91/100 | Train Loss: 0.8482 | Train Acc: 0.9997 | Val Loss: 0.8748 | Val Acc: 0.9890
 Epoch 92/100 | Train Loss: 0.8465 | Train Acc: 0.9999 | Val Loss: 0.8754 | Val Acc: 0.9883
 Epoch 93/100 | Train Loss: 0.8437 | Train Acc: 1.0000 | Val Loss: 0.8732 | Val Acc: 0.9886
 Epoch 94/100 | Train Loss: 0.8430 | Train Acc: 0.9998 | Val Loss: 0.8727 | Val Acc: 0.9883
 Epoch 95/100 | Train Loss: 0.8415 | Train Acc: 1.0000 | Val Loss: 0.8730 | Val Acc: 0.9890
 Epoch 96/100 | Train Loss: 0.8412 | Train Acc: 0.9998 | Val Loss: 0.8727 | Val Acc: 0.9893
 Epoch 97/100 | Train Loss: 0.8398 | Train Acc: 1.0000 | Val Loss: 0.8726 | Val Acc: 0.9890
 Epoch 98/100 | Train Loss: 0.8393 | Train Acc: 0.9999 | Val Loss: 0.8734 | Val Acc: 0.9883
 Epoch 99/100 | Train Loss: 0.8393 | Train Acc: 1.0000 | Val Loss: 0.8732 | Val Acc: 0.9897
 Epoch 100/100 | Train Loss: 0.8396 | Train Acc: 1.0000 | Val Loss: 0.8713 | Val Acc: 0.9897
Training complete!
Test accuracy: 0.992181947405828
CPU times: user 1min 48s, sys: 1.65 s, total: 1min 49s
Wall time: 1min 14s

In [ ]:
%%time

# ----------------- Apply dimensionality reduction -----------------
DIM_REDUCTION_METHOD = "GRP"  # options: "PCA", "ICA", "NMF", "TruncatedSVD", "GRP", "SRP"

X_train_np, X_val_np, X_test_np, reducer = reduce_dimensions(
    X_train_std, X_val_std, X_test_std,
    method=DIM_REDUCTION_METHOD,
    n_components=n_components_opt
)

print(f"✅ Dimensionality reduction using {DIM_REDUCTION_METHOD} complete. New feature dim: {X_train_np.shape[1]}")

# ------------------ LOAD Datasets ------------------------
train_dataset = ShapeFeatureDataset(X_train_np, y_train_idx)
val_dataset   = ShapeFeatureDataset(X_val_np,   y_val_idx)
test_dataset  = ShapeFeatureDataset(X_test_np,   y_test_idx)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0, pin_memory=False)
val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE, shuffle=False, num_workers=0, pin_memory=False)
test_loader  = DataLoader(test_dataset,   batch_size=BATCH_SIZE, shuffle=False, num_workers=0, pin_memory=False)

# Load model and optimizers
input_dim = X_train_np.shape[1]
num_classes = len(classes)
device = torch.device(f"cuda:{DEVICE_ID}")
model = MLPClassifier(input_dim, num_classes).to(device)
criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
optimizer = torch.optim.Adam(model.parameters(), lr=LR)
scheduler = ReduceLROnPlateau(optimizer, mode="min", factor=0.5, patience=2)

history = train_model(
    model=model,
    train_loader=train_loader,
    val_loader=val_loader,
    criterion=criterion,
    optimizer=optimizer,
    scheduler=scheduler,
    device=device,
    epochs=EPOCHS,
    log_dir=LOG_DIR+f"_{DIM_REDUCTION_METHOD}"
)

# ----------------- Load best model -----------------
# best_model_path = os.path.join(LOG_DIR, "checkpoints", "best_model.pth")
# model.load_state_dict(torch.load(best_model_path, map_location=device))
# model.to(device)
model.eval()

# ----------------- Evaluate on test set -----------------
def evaluate_test(model, loader, device):
    correct = 0
    total = 0
    with torch.no_grad():
        for X, y in loader:
            X, y = X.to(device), y.to(device)
            outputs = model(X)
            preds = outputs.argmax(dim=1)
            correct += (preds == y).sum().item()
            total += y.size(0)
    return correct / total

test_acc = evaluate_test(model, test_loader, device)
print("Test accuracy:", test_acc)

✅ Dimensionality reduction using GRP complete. New feature dim: 634
Starting the first epoch...
 Epoch 1/100 | Train Loss: 3.5143 | Train Acc: 0.2224 | Val Loss: 2.9026 | Val Acc: 0.3311
 Epoch 2/100 | Train Loss: 2.7559 | Train Acc: 0.3735 | Val Loss: 2.5725 | Val Acc: 0.4203
 Epoch 3/100 | Train Loss: 2.4281 | Train Acc: 0.4650 | Val Loss: 2.3434 | Val Acc: 0.4961
 Epoch 4/100 | Train Loss: 2.1846 | Train Acc: 0.5429 | Val Loss: 2.1551 | Val Acc: 0.5644
 Epoch 5/100 | Train Loss: 1.9919 | Train Acc: 0.6101 | Val Loss: 2.0020 | Val Acc: 0.6188
 Epoch 6/100 | Train Loss: 1.8382 | Train Acc: 0.6661 | Val Loss: 1.8652 | Val Acc: 0.6682
 Epoch 7/100 | Train Loss: 1.7079 | Train Acc: 0.7182 | Val Loss: 1.7497 | Val Acc: 0.7137
 Epoch 8/100 | Train Loss: 1.6073 | Train Acc: 0.7576 | Val Loss: 1.6448 | Val Acc: 0.7468
 Epoch 9/100 | Train Loss: 1.5220 | Train Acc: 0.7873 | Val Loss: 1.5532 | Val Acc: 0.7873
 Epoch 10/100 | Train Loss: 1.4438 | Train Acc: 0.8209 | Val Loss: 1.4879 | Val Acc: 0.8083
 Epoch 11/100 | Train Loss: 1.3839 | Train Acc: 0.8468 | Val Loss: 1.4191 | Val Acc: 0.8332
 Epoch 12/100 | Train Loss: 1.3332 | Train Acc: 0.8652 | Val Loss: 1.3687 | Val Acc: 0.8549
 Epoch 13/100 | Train Loss: 1.2941 | Train Acc: 0.8803 | Val Loss: 1.3179 | Val Acc: 0.8773
 Epoch 14/100 | Train Loss: 1.2588 | Train Acc: 0.8939 | Val Loss: 1.2846 | Val Acc: 0.8894
 Epoch 15/100 | Train Loss: 1.2268 | Train Acc: 0.9083 | Val Loss: 1.2474 | Val Acc: 0.9033
 Epoch 16/100 | Train Loss: 1.2049 | Train Acc: 0.9158 | Val Loss: 1.2205 | Val Acc: 0.9161
 Epoch 17/100 | Train Loss: 1.1784 | Train Acc: 0.9266 | Val Loss: 1.1977 | Val Acc: 0.9214
 Epoch 18/100 | Train Loss: 1.1634 | Train Acc: 0.9338 | Val Loss: 1.1732 | Val Acc: 0.9285
 Epoch 19/100 | Train Loss: 1.1435 | Train Acc: 0.9386 | Val Loss: 1.1536 | Val Acc: 0.9356
 Epoch 20/100 | Train Loss: 1.1297 | Train Acc: 0.9454 | Val Loss: 1.1352 | Val Acc: 0.9406
 Epoch 21/100 | Train Loss: 1.1181 | Train Acc: 0.9500 | Val Loss: 1.1255 | Val Acc: 0.9410
 Epoch 22/100 | Train Loss: 1.0984 | Train Acc: 0.9568 | Val Loss: 1.1142 | Val Acc: 0.9484
 Epoch 23/100 | Train Loss: 1.0877 | Train Acc: 0.9588 | Val Loss: 1.1051 | Val Acc: 0.9467
 Epoch 24/100 | Train Loss: 1.0809 | Train Acc: 0.9609 | Val Loss: 1.0921 | Val Acc: 0.9506
 Epoch 25/100 | Train Loss: 1.0737 | Train Acc: 0.9643 | Val Loss: 1.0786 | Val Acc: 0.9552
 Epoch 26/100 | Train Loss: 1.0650 | Train Acc: 0.9657 | Val Loss: 1.0753 | Val Acc: 0.9545
 Epoch 27/100 | Train Loss: 1.0577 | Train Acc: 0.9698 | Val Loss: 1.0725 | Val Acc: 0.9566
 Epoch 28/100 | Train Loss: 1.0491 | Train Acc: 0.9725 | Val Loss: 1.0562 | Val Acc: 0.9595
 Epoch 29/100 | Train Loss: 1.0393 | Train Acc: 0.9754 | Val Loss: 1.0480 | Val Acc: 0.9641
 Epoch 30/100 | Train Loss: 1.0360 | Train Acc: 0.9760 | Val Loss: 1.0475 | Val Acc: 0.9602
 Epoch 31/100 | Train Loss: 1.0282 | Train Acc: 0.9778 | Val Loss: 1.0421 | Val Acc: 0.9637
 Epoch 32/100 | Train Loss: 1.0204 | Train Acc: 0.9808 | Val Loss: 1.0363 | Val Acc: 0.9659
 Epoch 33/100 | Train Loss: 1.0198 | Train Acc: 0.9802 | Val Loss: 1.0252 | Val Acc: 0.9687
 Epoch 34/100 | Train Loss: 1.0142 | Train Acc: 0.9823 | Val Loss: 1.0269 | Val Acc: 0.9673
 Epoch 35/100 | Train Loss: 1.0074 | Train Acc: 0.9830 | Val Loss: 1.0215 | Val Acc: 0.9708
 Epoch 36/100 | Train Loss: 1.0031 | Train Acc: 0.9827 | Val Loss: 1.0212 | Val Acc: 0.9701
 Epoch 37/100 | Train Loss: 1.0022 | Train Acc: 0.9840 | Val Loss: 1.0144 | Val Acc: 0.9708
 Epoch 38/100 | Train Loss: 0.9976 | Train Acc: 0.9852 | Val Loss: 1.0110 | Val Acc: 0.9719
 Epoch 39/100 | Train Loss: 0.9946 | Train Acc: 0.9868 | Val Loss: 1.0085 | Val Acc: 0.9730
 Epoch 40/100 | Train Loss: 0.9900 | Train Acc: 0.9871 | Val Loss: 1.0016 | Val Acc: 0.9719
 Epoch 41/100 | Train Loss: 0.9866 | Train Acc: 0.9878 | Val Loss: 0.9977 | Val Acc: 0.9730
 Epoch 42/100 | Train Loss: 0.9814 | Train Acc: 0.9882 | Val Loss: 0.9982 | Val Acc: 0.9730
 Epoch 43/100 | Train Loss: 0.9798 | Train Acc: 0.9884 | Val Loss: 0.9973 | Val Acc: 0.9744
 Epoch 44/100 | Train Loss: 0.9751 | Train Acc: 0.9909 | Val Loss: 0.9904 | Val Acc: 0.9740
 Epoch 45/100 | Train Loss: 0.9764 | Train Acc: 0.9887 | Val Loss: 0.9890 | Val Acc: 0.9758
 Epoch 46/100 | Train Loss: 0.9701 | Train Acc: 0.9910 | Val Loss: 0.9853 | Val Acc: 0.9737
 Epoch 47/100 | Train Loss: 0.9677 | Train Acc: 0.9910 | Val Loss: 0.9805 | Val Acc: 0.9755
 Epoch 48/100 | Train Loss: 0.9647 | Train Acc: 0.9913 | Val Loss: 0.9798 | Val Acc: 0.9762
 Epoch 49/100 | Train Loss: 0.9628 | Train Acc: 0.9921 | Val Loss: 0.9782 | Val Acc: 0.9744
 Epoch 50/100 | Train Loss: 0.9596 | Train Acc: 0.9914 | Val Loss: 0.9757 | Val Acc: 0.9755
 Epoch 51/100 | Train Loss: 0.9583 | Train Acc: 0.9921 | Val Loss: 0.9726 | Val Acc: 0.9765
 Epoch 52/100 | Train Loss: 0.9571 | Train Acc: 0.9932 | Val Loss: 0.9706 | Val Acc: 0.9772
 Epoch 53/100 | Train Loss: 0.9541 | Train Acc: 0.9930 | Val Loss: 0.9703 | Val Acc: 0.9772
 Epoch 54/100 | Train Loss: 0.9544 | Train Acc: 0.9938 | Val Loss: 0.9695 | Val Acc: 0.9765
 Epoch 55/100 | Train Loss: 0.9492 | Train Acc: 0.9938 | Val Loss: 0.9690 | Val Acc: 0.9758
 Epoch 56/100 | Train Loss: 0.9488 | Train Acc: 0.9928 | Val Loss: 0.9694 | Val Acc: 0.9776
 Epoch 57/100 | Train Loss: 0.9485 | Train Acc: 0.9939 | Val Loss: 0.9639 | Val Acc: 0.9769
 Epoch 58/100 | Train Loss: 0.9444 | Train Acc: 0.9947 | Val Loss: 0.9622 | Val Acc: 0.9797
 Epoch 59/100 | Train Loss: 0.9443 | Train Acc: 0.9941 | Val Loss: 0.9650 | Val Acc: 0.9776
 Epoch 60/100 | Train Loss: 0.9420 | Train Acc: 0.9953 | Val Loss: 0.9608 | Val Acc: 0.9787
 Epoch 61/100 | Train Loss: 0.9403 | Train Acc: 0.9955 | Val Loss: 0.9634 | Val Acc: 0.9769
 Epoch 62/100 | Train Loss: 0.9397 | Train Acc: 0.9950 | Val Loss: 0.9589 | Val Acc: 0.9780
 Epoch 63/100 | Train Loss: 0.9367 | Train Acc: 0.9954 | Val Loss: 0.9610 | Val Acc: 0.9787
 Epoch 64/100 | Train Loss: 0.9344 | Train Acc: 0.9959 | Val Loss: 0.9580 | Val Acc: 0.9765
 Epoch 65/100 | Train Loss: 0.9348 | Train Acc: 0.9946 | Val Loss: 0.9547 | Val Acc: 0.9780
 Epoch 66/100 | Train Loss: 0.9326 | Train Acc: 0.9952 | Val Loss: 0.9529 | Val Acc: 0.9787
 Epoch 67/100 | Train Loss: 0.9341 | Train Acc: 0.9943 | Val Loss: 0.9541 | Val Acc: 0.9783
 Epoch 68/100 | Train Loss: 0.9297 | Train Acc: 0.9957 | Val Loss: 0.9551 | Val Acc: 0.9780
 Epoch 69/100 | Train Loss: 0.9308 | Train Acc: 0.9959 | Val Loss: 0.9514 | Val Acc: 0.9776
 Epoch 70/100 | Train Loss: 0.9287 | Train Acc: 0.9961 | Val Loss: 0.9476 | Val Acc: 0.9790
 Epoch 71/100 | Train Loss: 0.9259 | Train Acc: 0.9966 | Val Loss: 0.9481 | Val Acc: 0.9783
 Epoch 72/100 | Train Loss: 0.9255 | Train Acc: 0.9963 | Val Loss: 0.9473 | Val Acc: 0.9801
 Epoch 73/100 | Train Loss: 0.9240 | Train Acc: 0.9969 | Val Loss: 0.9460 | Val Acc: 0.9804
 Epoch 74/100 | Train Loss: 0.9236 | Train Acc: 0.9968 | Val Loss: 0.9434 | Val Acc: 0.9812
 Epoch 75/100 | Train Loss: 0.9214 | Train Acc: 0.9968 | Val Loss: 0.9451 | Val Acc: 0.9787
 Epoch 76/100 | Train Loss: 0.9211 | Train Acc: 0.9970 | Val Loss: 0.9400 | Val Acc: 0.9790
 Epoch 77/100 | Train Loss: 0.9195 | Train Acc: 0.9970 | Val Loss: 0.9395 | Val Acc: 0.9801
 Epoch 78/100 | Train Loss: 0.9189 | Train Acc: 0.9970 | Val Loss: 0.9422 | Val Acc: 0.9797
 Epoch 79/100 | Train Loss: 0.9202 | Train Acc: 0.9969 | Val Loss: 0.9399 | Val Acc: 0.9804
 Epoch 80/100 | Train Loss: 0.9167 | Train Acc: 0.9972 | Val Loss: 0.9409 | Val Acc: 0.9776
 Epoch 81/100 | Train Loss: 0.9088 | Train Acc: 0.9977 | Val Loss: 0.9339 | Val Acc: 0.9822
 Epoch 82/100 | Train Loss: 0.9052 | Train Acc: 0.9982 | Val Loss: 0.9330 | Val Acc: 0.9819
 Epoch 83/100 | Train Loss: 0.9022 | Train Acc: 0.9979 | Val Loss: 0.9306 | Val Acc: 0.9826
 Epoch 84/100 | Train Loss: 0.9012 | Train Acc: 0.9990 | Val Loss: 0.9329 | Val Acc: 0.9801
 Epoch 85/100 | Train Loss: 0.9010 | Train Acc: 0.9984 | Val Loss: 0.9325 | Val Acc: 0.9822
 Epoch 86/100 | Train Loss: 0.8996 | Train Acc: 0.9985 | Val Loss: 0.9295 | Val Acc: 0.9790
 Epoch 87/100 | Train Loss: 0.8999 | Train Acc: 0.9981 | Val Loss: 0.9306 | Val Acc: 0.9812
 Epoch 88/100 | Train Loss: 0.8982 | Train Acc: 0.9987 | Val Loss: 0.9290 | Val Acc: 0.9808
 Epoch 89/100 | Train Loss: 0.8984 | Train Acc: 0.9982 | Val Loss: 0.9263 | Val Acc: 0.9822
 Epoch 90/100 | Train Loss: 0.8968 | Train Acc: 0.9985 | Val Loss: 0.9277 | Val Acc: 0.9804
 Epoch 91/100 | Train Loss: 0.8982 | Train Acc: 0.9986 | Val Loss: 0.9288 | Val Acc: 0.9822
 Epoch 92/100 | Train Loss: 0.8968 | Train Acc: 0.9987 | Val Loss: 0.9276 | Val Acc: 0.9822
 Epoch 93/100 | Train Loss: 0.8933 | Train Acc: 0.9989 | Val Loss: 0.9249 | Val Acc: 0.9819
 Epoch 94/100 | Train Loss: 0.8915 | Train Acc: 0.9991 | Val Loss: 0.9256 | Val Acc: 0.9808
 Epoch 95/100 | Train Loss: 0.8910 | Train Acc: 0.9986 | Val Loss: 0.9253 | Val Acc: 0.9815
 Epoch 96/100 | Train Loss: 0.8911 | Train Acc: 0.9988 | Val Loss: 0.9245 | Val Acc: 0.9815
 Epoch 97/100 | Train Loss: 0.8886 | Train Acc: 0.9991 | Val Loss: 0.9234 | Val Acc: 0.9808
 Epoch 98/100 | Train Loss: 0.8885 | Train Acc: 0.9992 | Val Loss: 0.9249 | Val Acc: 0.9829
 Epoch 99/100 | Train Loss: 0.8891 | Train Acc: 0.9992 | Val Loss: 0.9233 | Val Acc: 0.9815
 Epoch 100/100 | Train Loss: 0.8879 | Train Acc: 0.9992 | Val Loss: 0.9236 | Val Acc: 0.9804
Training complete!
Test accuracy: 0.9886282871357498
CPU times: user 36.1 s, sys: 930 ms, total: 37.1 s
Wall time: 1min 18s

In [ ]:
%%time

# ----------------- Apply dimensionality reduction -----------------
DIM_REDUCTION_METHOD = "NMF"  # options: "PCA", "ICA", "NMF", "TruncatedSVD", "GRP", "SRP"

X_train_np, X_val_np, X_test_np, reducer = reduce_dimensions(
    X_train_std, X_val_std, X_test_std,
    method=DIM_REDUCTION_METHOD,
    n_components=n_components_opt
)

print(f"✅ Dimensionality reduction using {DIM_REDUCTION_METHOD} complete. New feature dim: {X_train_np.shape[1]}")

# ------------------ LOAD Datasets ------------------------
train_dataset = ShapeFeatureDataset(X_train_np, y_train_idx)
val_dataset   = ShapeFeatureDataset(X_val_np,   y_val_idx)
test_dataset  = ShapeFeatureDataset(X_test_np,   y_test_idx)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0, pin_memory=False)
val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE, shuffle=False, num_workers=0, pin_memory=False)
test_loader  = DataLoader(test_dataset,   batch_size=BATCH_SIZE, shuffle=False, num_workers=0, pin_memory=False)

# Load model and optimizers
input_dim = X_train_np.shape[1]
num_classes = len(classes)
device = torch.device(f"cuda:{DEVICE_ID}")
model = MLPClassifier(input_dim, num_classes).to(device)
criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
optimizer = torch.optim.Adam(model.parameters(), lr=LR)
scheduler = ReduceLROnPlateau(optimizer, mode="min", factor=0.5, patience=2)

history = train_model(
    model=model,
    train_loader=train_loader,
    val_loader=val_loader,
    criterion=criterion,
    optimizer=optimizer,
    scheduler=scheduler,
    device=device,
    epochs=EPOCHS,
    log_dir=LOG_DIR+f"_{DIM_REDUCTION_METHOD}"
)

# ----------------- Load best model -----------------
# best_model_path = os.path.join(LOG_DIR, "checkpoints", "best_model.pth")
# model.load_state_dict(torch.load(best_model_path, map_location=device))
# model.to(device)
model.eval()

# ----------------- Evaluate on test set -----------------
def evaluate_test(model, loader, device):
    correct = 0
    total = 0
    with torch.no_grad():
        for X, y in loader:
            X, y = X.to(device), y.to(device)
            outputs = model(X)
            preds = outputs.argmax(dim=1)
            correct += (preds == y).sum().item()
            total += y.size(0)
    return correct / total

test_acc = evaluate_test(model, test_loader, device)
print("Test accuracy:", test_acc)

✅ Dimensionality reduction using NMF complete. New feature dim: 634
Starting the first epoch...
 Epoch 1/100 | Train Loss: 3.8228 | Train Acc: 0.1560 | Val Loss: 3.4132 | Val Acc: 0.2255
 Epoch 2/100 | Train Loss: 3.3675 | Train Acc: 0.2277 | Val Loss: 3.1968 | Val Acc: 0.2660
 Epoch 3/100 | Train Loss: 3.1277 | Train Acc: 0.2757 | Val Loss: 2.9762 | Val Acc: 0.3126
 Epoch 4/100 | Train Loss: 2.9017 | Train Acc: 0.3298 | Val Loss: 2.7899 | Val Acc: 0.3574
 Epoch 5/100 | Train Loss: 2.6917 | Train Acc: 0.3829 | Val Loss: 2.6219 | Val Acc: 0.4093
 Epoch 6/100 | Train Loss: 2.5168 | Train Acc: 0.4320 | Val Loss: 2.4772 | Val Acc: 0.4431
 Epoch 7/100 | Train Loss: 2.3600 | Train Acc: 0.4813 | Val Loss: 2.3588 | Val Acc: 0.4769
 Epoch 8/100 | Train Loss: 2.2226 | Train Acc: 0.5263 | Val Loss: 2.2355 | Val Acc: 0.5228
 Epoch 9/100 | Train Loss: 2.0982 | Train Acc: 0.5690 | Val Loss: 2.1123 | Val Acc: 0.5690
 Epoch 10/100 | Train Loss: 1.9860 | Train Acc: 0.6077 | Val Loss: 2.0171 | Val Acc: 0.6010
 Epoch 11/100 | Train Loss: 1.8949 | Train Acc: 0.6420 | Val Loss: 1.9311 | Val Acc: 0.6316
 Epoch 12/100 | Train Loss: 1.8198 | Train Acc: 0.6698 | Val Loss: 1.8650 | Val Acc: 0.6590
 Epoch 13/100 | Train Loss: 1.7401 | Train Acc: 0.7004 | Val Loss: 1.7774 | Val Acc: 0.6895
 Epoch 14/100 | Train Loss: 1.6669 | Train Acc: 0.7286 | Val Loss: 1.7122 | Val Acc: 0.7265
 Epoch 15/100 | Train Loss: 1.6185 | Train Acc: 0.7464 | Val Loss: 1.6525 | Val Acc: 0.7457
 Epoch 16/100 | Train Loss: 1.5585 | Train Acc: 0.7702 | Val Loss: 1.6044 | Val Acc: 0.7582
 Epoch 17/100 | Train Loss: 1.5118 | Train Acc: 0.7919 | Val Loss: 1.5585 | Val Acc: 0.7696
 Epoch 18/100 | Train Loss: 1.4665 | Train Acc: 0.8056 | Val Loss: 1.5037 | Val Acc: 0.8080
 Epoch 19/100 | Train Loss: 1.4319 | Train Acc: 0.8201 | Val Loss: 1.4612 | Val Acc: 0.8254
 Epoch 20/100 | Train Loss: 1.4009 | Train Acc: 0.8349 | Val Loss: 1.4346 | Val Acc: 0.8339
 Epoch 21/100 | Train Loss: 1.3639 | Train Acc: 0.8507 | Val Loss: 1.3891 | Val Acc: 0.8517
 Epoch 22/100 | Train Loss: 1.3347 | Train Acc: 0.8633 | Val Loss: 1.3612 | Val Acc: 0.8652
 Epoch 23/100 | Train Loss: 1.3143 | Train Acc: 0.8675 | Val Loss: 1.3345 | Val Acc: 0.8681
 Epoch 24/100 | Train Loss: 1.2837 | Train Acc: 0.8861 | Val Loss: 1.3019 | Val Acc: 0.8908
 Epoch 25/100 | Train Loss: 1.2656 | Train Acc: 0.8898 | Val Loss: 1.2838 | Val Acc: 0.8880
 Epoch 26/100 | Train Loss: 1.2483 | Train Acc: 0.8987 | Val Loss: 1.2714 | Val Acc: 0.8915
 Epoch 27/100 | Train Loss: 1.2345 | Train Acc: 0.9035 | Val Loss: 1.2408 | Val Acc: 0.9075
 Epoch 28/100 | Train Loss: 1.2141 | Train Acc: 0.9108 | Val Loss: 1.2257 | Val Acc: 0.9093
 Epoch 29/100 | Train Loss: 1.2005 | Train Acc: 0.9163 | Val Loss: 1.2041 | Val Acc: 0.9161
 Epoch 30/100 | Train Loss: 1.1937 | Train Acc: 0.9209 | Val Loss: 1.1931 | Val Acc: 0.9225
 Epoch 31/100 | Train Loss: 1.1778 | Train Acc: 0.9250 | Val Loss: 1.1834 | Val Acc: 0.9196
 Epoch 32/100 | Train Loss: 1.1671 | Train Acc: 0.9290 | Val Loss: 1.1650 | Val Acc: 0.9307
 Epoch 33/100 | Train Loss: 1.1530 | Train Acc: 0.9355 | Val Loss: 1.1592 | Val Acc: 0.9292
 Epoch 34/100 | Train Loss: 1.1404 | Train Acc: 0.9411 | Val Loss: 1.1509 | Val Acc: 0.9331
 Epoch 35/100 | Train Loss: 1.1349 | Train Acc: 0.9424 | Val Loss: 1.1480 | Val Acc: 0.9299
 Epoch 36/100 | Train Loss: 1.1281 | Train Acc: 0.9462 | Val Loss: 1.1313 | Val Acc: 0.9385
 Epoch 37/100 | Train Loss: 1.1194 | Train Acc: 0.9481 | Val Loss: 1.1188 | Val Acc: 0.9435
 Epoch 38/100 | Train Loss: 1.1147 | Train Acc: 0.9490 | Val Loss: 1.1145 | Val Acc: 0.9442
 Epoch 39/100 | Train Loss: 1.1036 | Train Acc: 0.9538 | Val Loss: 1.0999 | Val Acc: 0.9531
 Epoch 40/100 | Train Loss: 1.0908 | Train Acc: 0.9563 | Val Loss: 1.0948 | Val Acc: 0.9523
 Epoch 41/100 | Train Loss: 1.0875 | Train Acc: 0.9584 | Val Loss: 1.0885 | Val Acc: 0.9531
 Epoch 42/100 | Train Loss: 1.0854 | Train Acc: 0.9580 | Val Loss: 1.0863 | Val Acc: 0.9523
 Epoch 43/100 | Train Loss: 1.0766 | Train Acc: 0.9622 | Val Loss: 1.0823 | Val Acc: 0.9523
 Epoch 44/100 | Train Loss: 1.0704 | Train Acc: 0.9646 | Val Loss: 1.0738 | Val Acc: 0.9580
 Epoch 45/100 | Train Loss: 1.0650 | Train Acc: 0.9659 | Val Loss: 1.0685 | Val Acc: 0.9566
 Epoch 46/100 | Train Loss: 1.0637 | Train Acc: 0.9678 | Val Loss: 1.0661 | Val Acc: 0.9591
 Epoch 47/100 | Train Loss: 1.0605 | Train Acc: 0.9669 | Val Loss: 1.0564 | Val Acc: 0.9609
 Epoch 48/100 | Train Loss: 1.0498 | Train Acc: 0.9731 | Val Loss: 1.0487 | Val Acc: 0.9659
 Epoch 49/100 | Train Loss: 1.0475 | Train Acc: 0.9737 | Val Loss: 1.0486 | Val Acc: 0.9602
 Epoch 50/100 | Train Loss: 1.0447 | Train Acc: 0.9719 | Val Loss: 1.0445 | Val Acc: 0.9612
 Epoch 51/100 | Train Loss: 1.0416 | Train Acc: 0.9731 | Val Loss: 1.0381 | Val Acc: 0.9644
 Epoch 52/100 | Train Loss: 1.0373 | Train Acc: 0.9756 | Val Loss: 1.0455 | Val Acc: 0.9598
 Epoch 53/100 | Train Loss: 1.0343 | Train Acc: 0.9761 | Val Loss: 1.0380 | Val Acc: 0.9662
 Epoch 54/100 | Train Loss: 1.0316 | Train Acc: 0.9765 | Val Loss: 1.0312 | Val Acc: 0.9676
 Epoch 55/100 | Train Loss: 1.0222 | Train Acc: 0.9798 | Val Loss: 1.0297 | Val Acc: 0.9659
 Epoch 56/100 | Train Loss: 1.0211 | Train Acc: 0.9798 | Val Loss: 1.0270 | Val Acc: 0.9676
 Epoch 57/100 | Train Loss: 1.0207 | Train Acc: 0.9794 | Val Loss: 1.0177 | Val Acc: 0.9687
 Epoch 58/100 | Train Loss: 1.0161 | Train Acc: 0.9809 | Val Loss: 1.0160 | Val Acc: 0.9705
 Epoch 59/100 | Train Loss: 1.0138 | Train Acc: 0.9818 | Val Loss: 1.0123 | Val Acc: 0.9691
 Epoch 60/100 | Train Loss: 1.0100 | Train Acc: 0.9830 | Val Loss: 1.0124 | Val Acc: 0.9687
 Epoch 61/100 | Train Loss: 1.0087 | Train Acc: 0.9832 | Val Loss: 1.0190 | Val Acc: 0.9683
 Epoch 62/100 | Train Loss: 1.0053 | Train Acc: 0.9838 | Val Loss: 1.0054 | Val Acc: 0.9698
 Epoch 63/100 | Train Loss: 1.0016 | Train Acc: 0.9827 | Val Loss: 1.0026 | Val Acc: 0.9716
 Epoch 64/100 | Train Loss: 1.0004 | Train Acc: 0.9841 | Val Loss: 1.0019 | Val Acc: 0.9740
 Epoch 65/100 | Train Loss: 1.0002 | Train Acc: 0.9822 | Val Loss: 1.0057 | Val Acc: 0.9712
 Epoch 66/100 | Train Loss: 0.9999 | Train Acc: 0.9834 | Val Loss: 0.9987 | Val Acc: 0.9733
 Epoch 67/100 | Train Loss: 0.9981 | Train Acc: 0.9839 | Val Loss: 0.9966 | Val Acc: 0.9740
 Epoch 68/100 | Train Loss: 0.9924 | Train Acc: 0.9855 | Val Loss: 0.9957 | Val Acc: 0.9737
 Epoch 69/100 | Train Loss: 0.9885 | Train Acc: 0.9860 | Val Loss: 0.9935 | Val Acc: 0.9730
 Epoch 70/100 | Train Loss: 0.9849 | Train Acc: 0.9873 | Val Loss: 0.9918 | Val Acc: 0.9726
 Epoch 71/100 | Train Loss: 0.9842 | Train Acc: 0.9863 | Val Loss: 0.9911 | Val Acc: 0.9748
 Epoch 72/100 | Train Loss: 0.9846 | Train Acc: 0.9874 | Val Loss: 0.9857 | Val Acc: 0.9744
 Epoch 73/100 | Train Loss: 0.9793 | Train Acc: 0.9894 | Val Loss: 0.9880 | Val Acc: 0.9733
 Epoch 74/100 | Train Loss: 0.9815 | Train Acc: 0.9885 | Val Loss: 0.9823 | Val Acc: 0.9765
 Epoch 75/100 | Train Loss: 0.9759 | Train Acc: 0.9893 | Val Loss: 0.9823 | Val Acc: 0.9744
 Epoch 76/100 | Train Loss: 0.9762 | Train Acc: 0.9889 | Val Loss: 0.9832 | Val Acc: 0.9737
 Epoch 77/100 | Train Loss: 0.9754 | Train Acc: 0.9889 | Val Loss: 0.9794 | Val Acc: 0.9723
 Epoch 78/100 | Train Loss: 0.9716 | Train Acc: 0.9903 | Val Loss: 0.9763 | Val Acc: 0.9762
 Epoch 79/100 | Train Loss: 0.9735 | Train Acc: 0.9891 | Val Loss: 0.9813 | Val Acc: 0.9737
 Epoch 80/100 | Train Loss: 0.9721 | Train Acc: 0.9893 | Val Loss: 0.9726 | Val Acc: 0.9769
 Epoch 81/100 | Train Loss: 0.9689 | Train Acc: 0.9908 | Val Loss: 0.9761 | Val Acc: 0.9744
 Epoch 82/100 | Train Loss: 0.9677 | Train Acc: 0.9905 | Val Loss: 0.9732 | Val Acc: 0.9765
 Epoch 83/100 | Train Loss: 0.9653 | Train Acc: 0.9905 | Val Loss: 0.9673 | Val Acc: 0.9758
 Epoch 84/100 | Train Loss: 0.9620 | Train Acc: 0.9914 | Val Loss: 0.9700 | Val Acc: 0.9780
 Epoch 85/100 | Train Loss: 0.9612 | Train Acc: 0.9915 | Val Loss: 0.9710 | Val Acc: 0.9783
 Epoch 86/100 | Train Loss: 0.9617 | Train Acc: 0.9917 | Val Loss: 0.9692 | Val Acc: 0.9776
 Epoch 87/100 | Train Loss: 0.9483 | Train Acc: 0.9946 | Val Loss: 0.9560 | Val Acc: 0.9794
 Epoch 88/100 | Train Loss: 0.9402 | Train Acc: 0.9950 | Val Loss: 0.9539 | Val Acc: 0.9794
 Epoch 89/100 | Train Loss: 0.9425 | Train Acc: 0.9941 | Val Loss: 0.9519 | Val Acc: 0.9790
 Epoch 90/100 | Train Loss: 0.9400 | Train Acc: 0.9955 | Val Loss: 0.9525 | Val Acc: 0.9801
 Epoch 91/100 | Train Loss: 0.9370 | Train Acc: 0.9958 | Val Loss: 0.9524 | Val Acc: 0.9801
 Epoch 92/100 | Train Loss: 0.9385 | Train Acc: 0.9946 | Val Loss: 0.9542 | Val Acc: 0.9794
 Epoch 93/100 | Train Loss: 0.9317 | Train Acc: 0.9956 | Val Loss: 0.9497 | Val Acc: 0.9804
 Epoch 94/100 | Train Loss: 0.9298 | Train Acc: 0.9964 | Val Loss: 0.9474 | Val Acc: 0.9794
 Epoch 95/100 | Train Loss: 0.9288 | Train Acc: 0.9961 | Val Loss: 0.9483 | Val Acc: 0.9801
 Epoch 96/100 | Train Loss: 0.9273 | Train Acc: 0.9963 | Val Loss: 0.9492 | Val Acc: 0.9794
 Epoch 97/100 | Train Loss: 0.9277 | Train Acc: 0.9972 | Val Loss: 0.9483 | Val Acc: 0.9804
 Epoch 98/100 | Train Loss: 0.9258 | Train Acc: 0.9969 | Val Loss: 0.9458 | Val Acc: 0.9801
 Epoch 99/100 | Train Loss: 0.9229 | Train Acc: 0.9969 | Val Loss: 0.9464 | Val Acc: 0.9790
 Epoch 100/100 | Train Loss: 0.9230 | Train Acc: 0.9966 | Val Loss: 0.9451 | Val Acc: 0.9819
Training complete!
Test accuracy: 0.9822316986496091
CPU times: user 52min 43s, sys: 11.8 s, total: 52min 55s
Wall time: 36min 14s