This script is to generate the class labels for the partwhole dataset

In [1]:
import os
from tqdm import tqdm
import pandas as pd

In [2]:
# Class names of every image
fulldata_path = r"/home/c/choton/beemachine/datasets/Bee_Full_Body_Segments/Images"
DATA_DIR = r"/home/c/choton/beemachine/datasets/Beemachine_Partwhole_v4/"

# Get list of classes
classes = os.listdir(fulldata_path)
species_dict = {}

for c in classes:
    images_path = os.path.join(fulldata_path, c)
    images = os.listdir(images_path)
    for image in images:
        image_name = image[:-4]
        species_dict[image_name] = c
image_names = list(species_dict.keys())
len(image_names)

8029

In [3]:
train_imgs_path = os.path.join(DATA_DIR, 'train', 'aug_images')
val_imgs_path = os.path.join(DATA_DIR, 'valid', 'images')
test_imgs_path = os.path.join(DATA_DIR, 'test', 'images')
train_images = os.listdir(train_imgs_path)
val_images = os.listdir(val_imgs_path)
test_images = os.listdir(test_imgs_path)
print(f"Images in dataset, train: {len(train_images)}, val: {len(val_images)}, test: {len(test_images)}")

Images in dataset, train: 34722, val: 1158, test: 771

In [4]:
# Preprocess image_names ONCE
normalized_species = {
    image_n.replace("._", "-_").replace(".jpg", ""): species_dict[image_n]
    for image_n in image_names
}
count = 0
species_y = {}
# Loop only once
for image_y in tqdm(train_images):
    for key, species in normalized_species.items():
        if key in image_y:
            count += 1
            species_y[image_y] = species
            break   # IMPORTANT: stop after first match
print(count)

100%|██████████| 34722/34722 [00:24<00:00, 1393.50it/s]

34722

In [5]:
train_dict = {'images': train_images}
train_df = pd.DataFrame(train_dict)
train_df['species'] = train_df['images'].map(species_y)
train_df

                                                  images               species
0      Bombus_distinguendus_GBIF_iNat_2573822774_2-jp...  Bombus_distinguendus
1      Bombus_bifarius_47362646_1_1_jpg.rf.bd7d10af8d...       Bombus_bifarius
2      BBW_Bombus_vandykei_4734_549ccb25-aae0-45c5-b0...       Bombus_vandykei
3      20DQ50CQ40DQG000G0DQ20TRQQYRKQTRSQZ0I0Z090TRXQ...       Bombus_fervidus
4      BBW_Bombus_sitkensis_1695_537b7c71-eed0-4246-a...      Bombus_sitkensis
...                                                  ...                   ...
34717  3L6LLZELIZTZ2RKH5RZH2R3ZIRYZMR2LQRLHMZVLMZOL2R...      Bombus_auricomus
34718  Bombus_bellicosus_GBIF_iNat_3301959651_3-jpg_j...     Bombus_bellicosus
34719  BBB_Bombus_affinis_693-2_1_jpg.rf.a52439e8cf4f...        Bombus_affinis
34720  5HTHXHDH6H6ZMLAZILAZXLBZ7L9Z5L9Z7LBZ4L6ZQL1ZUH...   Bombus_californicus
34721  5QV06QB0AQ6K8KAKMK1KIKOK7KAKHKUKGQPK8QD0RKBK8K...  Bombus_pensylvanicus

[34722 rows x 2 columns]

In [6]:
count = 0
species_y = {}
# Loop only once
for image_y in tqdm(val_images):
    for key, species in normalized_species.items():
        if key in image_y:
            count += 1
            species_y[image_y] = species
            break   # IMPORTANT: stop after first match
print(count)

  0%|          | 0/1158 [00:00<?, ?it/s]

100%|██████████| 1158/1158 [00:00<00:00, 1395.28it/s]

1158

In [7]:
valid_dict = {'images': val_images}
valid_df = pd.DataFrame(valid_dict)
valid_df['species'] = valid_df['images'].map(species_y)
valid_df

                                                 images              species
0     BBW_Bombus_appositus_23855_e5f978d9-d6e7-4322-...     Bombus_appositus
1     Bombus_lapidarius_iNat_12287097_1-jpg_jpg.rf.3...    Bombus_lapidarius
2     0HGRDZIROZ7RFZXRULHZ9L0R3ZYLNLKROZRZ9LYLNLZZTZ...  Bombus_vosnesenskii
3     Bombus_morio_GBIF_iNat_2603344712_9-jpg_jpg.rf...         Bombus_morio
4     Bombus_pratorum_iNat_21415168_1-jpg_jpg.rf.0db...      Bombus_pratorum
...                                                 ...                  ...
1153  BBB_Bombus_affinis_1026-2_1_jpg.rf.055960b6e3a...       Bombus_affinis
1154  5LVZXLBZHLHRMHYHEHZR9HRRNHHR2HAZ2H9Z2HAZ8LWZ8L...     Bombus_auricomus
1155  BBW_Bombus_flavifrons_1337_536808c9-deb0-4c8b-...    Bombus_flavifrons
1156  Bombus_alpinus_iNat_54101328_1-jpg_jpg.rf.38ff...       Bombus_alpinus
1157  BBB_Bombus_affinis_1201-3_1_jpg.rf.0b731576849...       Bombus_affinis

[1158 rows x 2 columns]

In [8]:
count = 0
species_y = {}
# Loop only once
for image_y in tqdm(test_images):
    for key, species in normalized_species.items():
        if key in image_y:
            count += 1
            species_y[image_y] = species
            break   # IMPORTANT: stop after first match
print(count)

100%|██████████| 771/771 [00:00<00:00, 1367.09it/s]

771

In [9]:
test_dict = {'images': test_images}
test_df = pd.DataFrame(test_dict)
test_df['species'] = test_df['images'].map(species_y)
test_df

                                                images            species
0    Bombus_robustus_GBIF_iNat_2814215056_7-jpg_jpg...    Bombus_robustus
1    5QV06QB0AQ6K8KAK8K1KLKVK7KAKUQLSXK2K5QB0UQ305K...   Bombus_appositus
2    60CQ70CQ6000E0FRQQH0E000IQ3R20FRQQTR20L090YRE0...   Bombus_appositus
3    BBW_Bombus_appositus_28231_846be2d2-b3b3-4947-...   Bombus_appositus
4    Bombus_hortulanus_GBIF_iNat_2028461117_1-jpg_j...  Bombus_hortulanus
..                                                 ...                ...
766  Bombus_medius_GBIF_iNat_1990632513_4-jpg_jpg.r...      Bombus_medius
767  1KMKDKXKUKUQT0VQHS6QRS2QRSUQAKHKUK4Q9KSKT01QLS...   Bombus_perplexus
768  BBW_Bombus_appositus_44103_4ece66ab-25be-459e-...   Bombus_appositus
769  AL0ZTLQZNL5RFZSRTZKRTZKRTZQRJZ7RYZRZYZ7ROZFLOZ...    Bombus_fervidus
770  80K0E0S020DQM0TQ40FQLQ9RYK1RHQ3R0QZ0SQURM01RFK...   Bombus_insularis

[771 rows x 2 columns]

In [10]:
train_df_path = os.path.join(DATA_DIR, 'train_labels.csv')
val_df_path = os.path.join(DATA_DIR, 'val_labels.csv')
test_df_path = os.path.join(DATA_DIR, 'test_labels.csv')
train_df.to_csv(train_df_path, index=False)
valid_df.to_csv(val_df_path, index=False)
test_df.to_csv(test_df_path, index=False)

In [12]:
set(test_df['species'])-set(train_df['species'])

{'Bombus_breviceps',
 'Bombus_laesus',
 'Bombus_trinominatus',
 'Bombus_tucumanus',
 'Bombus_tunicatus',
 'Bombus_turkestanicus',
 'Bombus_vestalis',
 'Bombus_wilmattae'}

In [13]:
set(valid_df['species'])-set(train_df['species'])

{'Bombus_laesus',
 'Bombus_lantschouensis',
 'Bombus_modestus',
 'Bombus_quadricolor'}

In [15]:
len(set(train_df['species'])), set(train_df['species'])

(149,
 {'Bombus_affinis',
  'Bombus_alpinus',
  'Bombus_appositus',
  'Bombus_ardens',
  'Bombus_argillaceus',
  'Bombus_armeniacus',
  'Bombus_ashtoni',
  'Bombus_atripes',
  'Bombus_auricomus',
  'Bombus_baeri',
  'Bombus_balteatus',
  'Bombus_barbutellus',
  'Bombus_bellicosus',
  'Bombus_bicoloratus',
  'Bombus_bifarius',
  'Bombus_bimaculatus',
  'Bombus_bohemicus',
  'Bombus_borealis',
  'Bombus_brachycephalus',
  'Bombus_brasiliensis',
  'Bombus_butteli',
  'Bombus_californicus',
  'Bombus_caliginosus',
  'Bombus_campestris',
  'Bombus_centralis',
  'Bombus_citrinus',
  'Bombus_coccineus',
  'Bombus_confusus',
  'Bombus_consobrinus',
  'Bombus_coreanus',
  'Bombus_crotchii',
  'Bombus_cryptarum',
  'Bombus_cullumanus',
  'Bombus_dahlbomii',
  'Bombus_diligens',
  'Bombus_distinguendus',
  'Bombus_diversus',
  'Bombus_excellens',
  'Bombus_eximius',
  'Bombus_fervidus',
  'Bombus_festivus',
  'Bombus_flavescens',
  'Bombus_flavidus',
  'Bombus_flavifrons',
  'Bombus_formosellus',
  'Bombus_franklini',
  'Bombus_fraternus',
  'Bombus_frigidus',
  'Bombus_funebris',
  'Bombus_genalis',
  'Bombus_gerstaeckeri',
  'Bombus_griseocollis',
  'Bombus_haematurus',
  'Bombus_haemorrhoidalis',
  'Bombus_handlirschi',
  'Bombus_hedini',
  'Bombus_honshuensis',
  'Bombus_hortorum',
  'Bombus_hortulanus',
  'Bombus_humilis',
  'Bombus_huntii',
  'Bombus_hyperboreus',
  'Bombus_hypnorum',
  'Bombus_hypocrita',
  'Bombus_ignitus',
  'Bombus_impatiens',
  'Bombus_insularis',
  'Bombus_irisanensis',
  'Bombus_johanseni',
  'Bombus_jonellus',
  'Bombus_kirbiellus',
  'Bombus_kluanensis',
  'Bombus_koreanus',
  'Bombus_lapidarius',
  'Bombus_lapponicus',
  'Bombus_longipennis',
  'Bombus_longipes',
  'Bombus_lucorum',
  'Bombus_macgregori',
  'Bombus_magnus',
  'Bombus_margreiteri',
  'Bombus_medius',
  'Bombus_melaleucus',
  'Bombus_melanopygus',
  'Bombus_melanurus',
  'Bombus_mendax',
  'Bombus_mesomelas',
  'Bombus_mexicanus',
  'Bombus_mixtus',
  'Bombus_monticola',
  'Bombus_morio',
  'Bombus_morrisoni',
  'Bombus_mucidus',
  'Bombus_muscorum',
  'Bombus_natvigi',
  'Bombus_neoboreus',
  'Bombus_nevadensis',
  'Bombus_niveatus',
  'Bombus_norvegicus',
  'Bombus_occidentalis',
  'Bombus_opifex',
  'Bombus_opulents',
  'Bombus_pascuorum',
  'Bombus_patagiatus',
  'Bombus_pauloensis',
  'Bombus_pensylvanicus',
  'Bombus_perplexus',
  'Bombus_persicus',
  'Bombus_picipes',
  'Bombus_polaris',
  'Bombus_pomorum',
  'Bombus_pratorum',
  'Bombus_pseudobaicalensis',
  'Bombus_pullatus',
  'Bombus_pyrenaeus',
  'Bombus_pyrosoma',
  'Bombus_robustus',
  'Bombus_rubicundus',
  'Bombus_ruderarius',
  'Bombus_ruderatus',
  'Bombus_rufipes',
  'Bombus_rufocinctus',
  'Bombus_rupestris',
  'Bombus_sandersoni',
  'Bombus_schrencki',
  'Bombus_semenovianus',
  'Bombus_semenoviellus',
  'Bombus_sibricus',
  'Bombus_sichelii',
  'Bombus_sitkensis',
  'Bombus_sonani',
  'Bombus_soroeensis',
  'Bombus_sporadicus',
  'Bombus_steindacheneri',
  'Bombus_subterraneus',
  'Bombus_suckleyi',
  'Bombus_sylvarum',
  'Bombus_sylvestris',
  'Bombus_sylvicola',
  'Bombus_ternarius',
  'Bombus_terricola',
  'Bombus_transversalis',
  'Bombus_trifasciatus',
  'Bombus_vagans',
  'Bombus_vancouverensis',
  'Bombus_vandykei',
  'Bombus_variabilis',
  'Bombus_vosnesenskii',
  'Bombus_zonatus'})